import React from "react";
import "./About.css";

const About = () => {
  return (
    <div>
      <div className="parentabout">
        <div className="aboutintro mb-5 ">
          <div className="aboutleft   p-5">
            <p>Welcome to Nerolife</p>
            <h1 className="display-4">What We're All About</h1>
          </div>
          <div className="aboutright p-5">
            <p>
              CLUB. LIFE. PERSONIFIED
              <br /> “WE SUGGEST EVENTS TO THEM WHO KNOWS WHAT THEY WANT AND
              EVEN TO THEM WHO DON’T KNOW WHAT THEY WANT, AS PER THEIR
              PREFERENCE “
            </p>
          </div>
        </div>

        <div className="aboutintro d-flex mb-5 ">
          <div className="aboutleft   p-5">
            <h1 className="display-4">ABOUT NEROLIFE NETWORKS:</h1>
          </div>
          <div className="aboutright p-5">
            <p>
              NEROLIFE NETWORKS IS AN INITIATIVE DEDICATED TOWARDS NIGHTLIFE
              SOCIAL & CLUB CULTURE TO PROVIDE COMPREHENSIVE SOLUTIONS AS AN
              AGGREGATOR BETWEEN EVENT DRIVEN CONSUMERS & MEDIA ENTERTAINMENT
              OUTLETS AS IN NIGHTCLUBS, PUBS ETC. WHERE SOCIAL EVENTS INVOLVING
              ELECTRONIC MUSICIANS & PRODUCERS, DJ’S PERFORMING LIVE MUSIC ARE
              ORGANIZED ON REGULAR BASIS TOWARDS PUBLIC ENTERTAINMENT.
              <br />
              <br />
              BEING A CUSTOMER CENTRIC COMPANY, SINCE INCEPTION, WE’VE DEDICATED
              OUR RESOURCES CONSIDERABLY TOWARDS CREATING A SYSTEM BY OBSESSING
              OVER CONSUMERS FIRST AND THEIR REQUIREMENTS THEN REVERSE
              ENGINEERED TO DESIGN SOLUTIONS WHICH ENDURES A PERFECT BALANCE FOR
              BUSINESS REQUIREMENTS OF ENTERTAINMENT OUTLETS TO MATCH WITH
              CONSUMER TASTE & PREFERENCE CONSISTENCY.
              <br />
              <br />
              WITH BREAK THROUGH TECHNOLOGY, IMPLEMATION OF COMPATIBLE
              ANALYTICS, OUR SYSTEM ALLOWS EVERY INDIVIDUAL CONSUMER TO EXPLORE
              THE CATEGORY OF MUSIC & TYPE OF EVENTS THEY’D WANT TO PARTICIPATE
              IN WITH SUGGESTIONS OF OUTLETS PERFORMING THE SAME CATEGORY OF
              MUSIC & TYPE OF EVENT ACCORDING TO CONSUMER’S OWN TASTE &
              PREFERENCE ALONGSIDE KEY INFORMATIONS TO MAKE INFORMED DECISIONS
              OVER REGULARLY INVITED OR 3RD PARTY REFERRED EVENTS.
              <br />
              <br />
              OUR SYSTEM PROVIDES ENTERTAINMENT OUTLETS KEY INSIGHTS ABOUT THEIR
              REGULAR CUSTOMERS, CUSTOMER OUTLOOK & PREFERENCE STATISTICALLY AS
              IN CATEGORY OF MUSIC OR TYPE OF EVENTS CUSTOMERS ARE INTERESTED IN
              WITH ANALYTICS & PROVIDE SUGGESTIONS TO ORGANIZE EVENTS AS PER
              CONSUMER PREFERENCE OVER ASSUMPTIONS OR 3RD PARTY PROPOSITIONS.
              <br />
              <br />A PLATFORM CRAFTED TO SECURE A MEANINGFUL RELATIONSHIP
              BETWEEN ENTERTAINMENT OUTLETS AND STRONG GROUP OF CUSTOMER BASE
              RESPECTIVELY.
            </p>
          </div>
        </div>

        <div className="aboutintro d-flex mb-5">
          <div className="aboutleft   p-5">
            <h1 className="display-4">WHEN WE STARTED:</h1>
          </div>
          <div className="aboutright p-5">
            <p>
              NEROLIFE, ORIGINALLY INCEPTED ON JULY 2018, STARTED OPERATIONS ON
              BOOTSTRAP BASIS AS A SUBSIDY EVENT MANAGEMENT COMPANY IN THE
              NIGHTLIFE BASED CULTURE OF MEDIA ENTERTAINMENT INDUSTRY TOWARDS
              EVENT CURATION WITH THE FOUNDERS ENGAGING COMBINATION OF WIDELY
              VERSATILE INTERNAL ASSOCIATIONS, MUSIC PRODUCERS, SOCIAL FIGURES &
              MEDIA INFLUENCERS AND HENCE THE TERM NETWORKS WAS ADDED. AS FOR
              EVENTS ORGANIZED, WE CURATED CONCEPT NIGHTS THROUGH WHICH WE
              LIMITED THE SCOPE OF MASS INTERVENTION BY INCREASING REACTION &
              INTEREST OF MUSIC CATEGORY & EVENT TYPE SPECIFIC TARGET AUDIENCE.
              WITH CONCEPTS LIKE “THE BASEMENT” WE FOCUSED ON GROUPS &
              COMMUNITIES HAVING PREFERENCE OF FOLLOWING HIP-HOP/BASS CULTURE
              WITH LIVE ELECTRONIC MUSIC. WITH CONCEPTS LIKE “D.O.T CULTURE” WE
              REACHED OUT FOR GROUPS & COMMUNITIES HAVING PREFERENCE ON URBAN
              HOUSE & TECHNO JAMS TO PROJECT FOOTFALL. EACH CONCEPT NIGHTS WE
              DESIGNED WERE DRESSED FOR A SPECIFIC GROUP OF ENTHUSIASTS &
              ACTIVISTS WITH RESPECT TO THE PARTICULAR CONCEPT RESULTED IN HIGH
              REACTION AND RESPONSE OVER MASS INTERVENTION.
            </p>
          </div>
        </div>

        <div className="aboutintro d-flex mb-5">
          <div className="aboutleft   p-5">
            <h1 className="display-4">WE HAVE FACED CHALLENGES TOO:</h1>
          </div>
          <div className="aboutright p-5">
            <p>
              POST DESIGNING & PROGRAMMING OF ANY EVENT, WE HAVE ALWAYS HAD
              FOLLOWED INDUSTRY SPECIFIC TRENDS & TRADITIONAL MEASUREMENTS BY
              REACHING OUT TO POTENTIAL EVENT DRIVEN CONSUMERS EXPONENTIALLY
              THROUGH MULTIPLE CHANNELS OF COMMUNICATION. LIKE MANY, OUR
              UPSTREAM EXPERIENCES WERE INVOLVED WITH UBER EXPOSED PAGE 3
              CONTENTS & SATISFIED CUSTOMERS AS BACK BONE TO OUR OPERATIONS BUT
              WE UNDERSTOOD THERE IS A LIMITED LEARNING CURVE TO SUCCESS
              COMPARED TO HIDDEN ARRAYS OF OPPORTUNITY WHILE DOWNSTREAMING
              ENDURANCE OF FAILURES. ON DECEMBER 2018, WHILE HOSTING A NIGHTCLUB
              EVENT IN A POSH HOTEL, ONE GROUP OF MEMBERS AMONGST MANY ATTENDING
              THE EVENT LEFT TOGETHER HALFWAY THROUGH THE GIG IN FAVOR OF AN
              ALTERNATIVE CATEGORY OF MUSIC ON ANOTHER OUTLET. ON AUGUST 2019,
              WE OBSERVED MULTIPLE SMALL GROUPS OF CUSTOMERS KEPT SWITCHING BACK
              AND FORTH BETWEEN 2 FAMED OUTLETS OF DISTINCTIVE HOTELS HOSTING
              HIGHLY RATED INTERNATIONAL ACTS. AS RECENT AS FEBRUARY 2020, WHILE
              HOSTING AN EVENT IN A PREMIUM OUTLET, INDIVIDUAL CUSTOMERS
              ATTENDING THE GIG WOULD GO & EXPLORE EVERY PREMIUM OUTLET NEARBY
              BEFORE JOINING US BACK AGAIN FOR THE NIGHT. FURTHER CASE STUDY OF
              TRADITIONAL PRACTICES, UNDER MULTIPLE SCENARIOS, WE NOTICED A
              CONCERNING PATTERN OF CONSISTENT DESCREASING CUSTOMER BANDWIDTH
              I.E. DECREASE OF AVERAGE CONVERTION TO REACH (CPR VALUE) OR
              FOOTFALL, DYNAMIC INFLATION RATE, DECREASE OF AVERAGE EXPENDITURE
              PER CUSTOMER (APC VALUE) OR REVENUE, INCREASE OF COST PER
              ACQUISITION (CPA VALUE) OR MARKETING COST, COMBINATION OF WHICH
              ARE SLOWING DOWN THE EVENT DRIVEN CONSUMER INDUSTRY. PROMOTIONALS
              IN THE MARKET PLACE ARE GUIDED TOWARDS ATTRACTING CUSTOMERS
              THROUGH ASSUMPTIONS & EXPERIENCES WITHOUT DATA DRIVEN
              ACKNOWLEDGEMENT OF CUSTOMER PREFERENCE RESULTING A STEEP FALL IN
              CUSTOMER RESPONSE. CUSTOMERS ARE TARGETTED & COMMUNICATED IN MASS
              WITH MULTIPLE EVENT INVITATIONS & PROMOTIONAL MESSAGES ON EVERYDAY
              BASIS WITHOUT CUSTOMER CONSENT YEILDING VERY LIMITED RESPONSE ALSO
              RESULTING A STEEP FALL IN CUSTOMER RESPONSE. DESPITE UTILIZATION
              OF KEY INSIGHTS ON EVENT INFOMERCIALS, LACK OF SEGREGATED CUSTOMER
              PREFERENCE KNOWLEDGE WITH DATA AMONGST THE INDUSTRY IS PREVENTING
              TO NAVIGATE EVENTS AS PER CUSTOMER PREFERENCE CAUSING CUSTOMER
              IN-ACTION WHICH IS ALSO DECREASING CONVERTION EFFICIENCY ON
              REGULAR BASIS.
            </p>
          </div>
        </div>

        <div className="aboutintro d-flex mb-5">
          <div className="aboutleft   p-5">
            <h1 className="display-4">DIFFERENCE WE MAKE:</h1>
          </div>
          <div className="aboutright p-5">
            <p>
              “ WE SUGGEST EVENTS TO CONSUMERS WHO KNOWS WHAT THEY WANT AND EVEN
              TO THEM WHO DON’T KNOW WHAT THEY WANT, AS PER THEIR PREFERENCE “
              THROUGH OUT THE BUSY SCHEDULE OF EVERY UBER MILLENIAL, CONSUMERS
              ARE LOOKING FOR COMPANIES WHO CAN FILTER ENTERTAINMENT EVENTS FOR
              THEM BY SORTING INFORMATIONS AS PER INDIVIDUAL CUSTOMER TASTE,
              PREFERENCE & LIFE STYLE GUIDED BY SMART SUGGESTIONS VIA. SMART
              ADVERTISEMENTS BY REACHING OUT TO THE RIGHT PEOPLE ON THE RIGHT
              OCCASION OVER TRADITIONAL PRACTICES SAVING THEIR LEISURE TIME FOR
              THEMSELVES. OUR TEAM AT NEROLIFE NETWORKS, SERVES ITS PURPOSE OF
              EXISTENCE BY PROVIDING SOLUTIONS & SERVICES THAT REPRESENTS
              INDIVIDUAL CUSTOMER ENTERTAINMENT PREFERENCE & INTEREST TO
              ENTERTAINMENT OUTLETS INVOLVING MULTIPLE CATEGORY OF MUSIC & TYPE
              OF EVENTS FOR BETTER UNDERSTANDING OF CUSTOMER NEEDS TO MATCH
              OUTLET’S BUSINESS REQUIREMENTS.
            </p>
          </div>
        </div>

        <div className="aboutintro d-flex mb-5">
          <div className="aboutleft   p-5">
            <h1 className="display-4">PRODUCT:</h1>
          </div>
          <div className="aboutright p-5">
            <p>
              NIGHTCUBE © NEROLIFE NETWORKS IS INDIA’S FIRST DIGITAL NIGHTLIFE
              BASED INFOTAINMENT & CUSTOMER MANAGEMENT PLATFORM DESIGNATED FOR
              EVENT DRIVEN CUSTOMERS & ENTERTAINMENT OUTLETS CONDUCTING EVENTS.
              NIGHTCUBE REPRESENTS CUSTOMER ENTERTAINMENT PREFERENCE TO
              ENTERTAINMENT OUTLETS INVOLVING MULTIPLE CATEGORY OF MUSIC & TYPE
              OF EVENTS FOR BETTER UNDERSTANDING OF CUSTOMER NEEDS TO MATCH
              OUTLET’S BUSINESS REQUIREMENTS. WITH BREAK THROUGH MEDIA SPEC
              TECHNOLOGY & DATA DRIVEN CRM ANALYTICS WE AIM TO BRING MEDIA AND
              ENTERTAINMENT SERVICES TO THE EVENT DRIVEN CONSUMERS WITH EVENTS
              OF THEIR OWN PREFERENCE. WE TAKE PRIDE IN UTMOST CONSUMER
              SATISFACTION & CLIENTS BUSINESS EFFICIENCY AND MAINTAIN COMPLETE
              TRANSPARENCY AMONGST ALL ENTITIES INVOLVED. WE ASPIRE INNOVATION,
              TECHNOLOGY & OPENNESS AND ARE EAGER TOWARDS EVERYONE’S
              CONTRIBUTION OF FEEDBACK & SUGGESTIONS. OUR TEAM DEDICATES HOURS
              IN DEVELOPING & CAREFULLY CRAFTING EACH NEW UPDATE FOR UTMOST
              CUSTOMER SATISFACTION.
            </p>
          </div>
        </div>

        <div className="aboutintro d-flex mb-5">
          <div className="aboutleft   p-5">
            <h1 className="display-4">INDUSTRY B2C:</h1>
          </div>
          <div className="aboutright p-5">
            <p>
              THROUGH OUT THE BUSY SCHEDULE OF EVERY UBER MILLENIAL, CONSUMERS
              ARE LOOKING FOR COMPANIES WHO CAN FILTER ENTERTAINMENT EVENTS FOR
              THEM BY SORTING INFORMATIONS AS PER INDIVIDUAL CUSTOMER TASTE,
              PREFERENCE & LIFE STYLE GUIDED BY SMART SUGGESTIONS VIA. SMART
              ADVERTISEMENTS BY REACHING OUT TO THE RIGHT PEOPLE ON THE RIGHT
              OCCASION OVER TRADITIONAL PRACTICES SAVING THEIR LEISURE TIME FOR
              THEMSELVES. INDUSTRY B2B: NEROLIFE NETWORKS 2PROVIDES SOLUTIONS &
              SERVICES THAT REPRESENTS INDIVIDUAL CUSTOMER ENTERTAINMENT
              PREFERENCE & INTEREST TO ENTERTAINMENT OUTLETS INVOLVING MULTIPLE
              CATEGORY OF MUSIC & TYPE OF EVENTS FOR BETTER UNDERSTANDING OF
              CUSTOMER NEEDS TO MATCH OUTLET’S BUSINESS REQUIREMENTS.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default About;
