import React from "react";
import { Link } from "react-router-dom";

const Privacy = () => {
  return (
    <div>
      <figure class="text-center">
        <blockquote class="blockquote">
          <p className="display-1 m-5">Privacy Policy</p>
        </blockquote>
        <figcaption class="blockquote-footer">
          THIS PRIVACY STATEMENT APPLIES TO THE SITES AND APPS WHERE IT APPEARS
          TO BE “ AS IS “
          <p className="m-5">
            THIS STATEMENT DESCRIBES HOW WE TREAT ANY OF YOUR PERSONAL
            INFORMATION WE COLLECT ON THIS SITE. IT ALSO INCLUDES COMMUNICATION
            IN PHONE OR EMAIL INTERACTIONS YOU HAVE WITH US. OUR PRIVACY
            STATEMENT HAS BEEN DESIGNED WITH YOUR COMFORT IN MIND. HOW THE
            POLICY APPLIES TO YOU WILL DEPENDS ON HOW YOU INTERACT WITH US. YOUR
            CHOICES AND RIGHTS UNDER EACH SCENARIO ARE EXPLAINED IN MORE
            DETAILED FORMAT.
          </p>
          <p className="m-5">
            <dl className="row">
              <dt className="col-sm-3">
                WHAT INFORMATION WE HAVE & WHERE WE GET IT:
              </dt>
              <dd className="col-sm-9">
                <p>
                  WE COLLECT AND STORE DIFFERENT TYPES OF INFORMATION ABOUT YOU
                  WHEN YOU CREATE AN ACCOUNT, CREATE BOOKINGS, RSVP EVENTS,
                  CONTACT US, AND USE OUR WEBSITES, SOCIAL MEDIA AND ANY OTHER
                  DIGITAL MEDIA PLATFORMS OPERATING UNDER US.
                </p>
              </dd>

              <dt className="col-sm-3">HOW WE USE YOUR INFORMATION & WHY:</dt>
              <dd className="col-sm-9">
                <p>
                  WE COLLECT AND USE YOUR INFORMATION FOR LOTS OF REASONS SUCH
                  AS UNDERSTANDING YOUR MUSIC INTEREST, UNDERSTANDING YOUR
                  PREFERENCES, FILTERING EVENTS OF YOUR CHOICES, SHARING LATEST
                  NEWS & UPDATES, FOR MARKETING PURPOSES, IMPROVING OUR
                  SOLUTIONS & SERVICES AND AS OTHERWISE IF REQUIRED BY LAW
                </p>
              </dd>

              <dt className="col-sm-3">WHO WE SHARE YOUR DATA WITH & WHY:</dt>
              <dd className="col-sm-9">
                <p>
                  WE RESPECT YOUR PRIVACY. WE DO NOT RENT, OUTSOURCE, SELL YOUR
                  INFORMATION TO ANYONE OR ANYWHERE OR 3RD PARTIES WITHOUT YOUR
                  APPROVAL OR PRIOR CONSENT. WE USE YOUR COLLECTIBLE INFORMATION
                  FOR DATA ANALYTICS AND SEGREGATION PURPOSES INTERNALLY TO
                  IMPROVE ACCURACY TOWARDS AGGREGATED SOLUTIONS & SERVICES.
                </p>
              </dd>

              <dt className="col-sm-3">YOUR CHOICES & RIGHTS:</dt>
              <dd className="col-sm-9">
                <p>
                  AMONG OTHER RIGHTS, YOU CAN CHOOSE WHETHER TO RECEIVE
                  MARKETING & PROMOTIONAL MATERIALS FROM US TIME TO TIME. YOU
                  ALSO HAVE THE RIGHT TO ACCESS THE INFORMATION WE HAVE ABOUT
                  YOU.
                </p>
              </dd>

              <dt className="col-sm-3">LOOKING AFTER YOUR INFORMATION:</dt>
              <dd className="col-sm-9">
                <p>
                  WE TAKE STANDARD STEPS & MEASURES TO ENSURE YOUR INFORMATION
                  IS PROTECTED AND SECURE IN OUR ACTIVE SERVERS AND WE MAKE SURE
                  TO DELETE IT SECURELY WHEN YOU ARE NO LONGER A PART OF OUR
                  FAMILY.
                </p>
              </dd>

              <dt className="col-sm-3">CONTACT US:</dt>
              <dd className="col-sm-9">
                <p>
                  NEROLIFE NETWORKS PVT. LTD. PROVIDES TECHNOLOGY BASED IF YOU
                  HAVE ANY QUESTIONS OR QUERIES ABOUT THIS STATEMENT, OR HOW WE
                  HANDLE YOUR INFORMATION, GET IN TOUCH WITH US
                </p>
              </dd>

              <dt className="col-sm-3">
                WHAT INFORMATION WE HAVE & WHERE WE GET IT:
              </dt>
              <dd className="col-sm-9">
                <p>
                  WE COLLECT INFORMATION FROM AND ABOUT YOU. CONTACT AND BILLING
                  INFORMATION. WHEN YOU CREATE AN ACCOUNT, CREATE A BOOKING OR
                  RESERVATION (RSVP), OR APPLY FOR NIGHTCUBE MEMBERSHIP. ON
                  UPDATED VERSIONS, EXAMPLE ONCE WE ADD TRANSACTION/BILLING
                  LINKS TO OUR PLATFORM, WE MAY COLLECT YOUR CONTACT AND BILLING
                  INFORMATION, SUCH AS YOUR NAME, STREET ADDRESS, ZIP CODE,
                  EMAIL, PHONE NUMBER AND CREDIT CARD NUMBER .
                </p>
              </dd>

              <dt className="col-sm-3">BACKGROUND & DEVELOPMENT :</dt>
              <dd className="col-sm-9">
                <p>
                  THE FOLLOWING ATTACHMENT PROVIDES RELATIVE INFORMATION TOWARDS
                  THE BACKGROUND & DEVELOPMENT
                </p>
              </dd>

              <dt className="col-sm-3">CONTACT US</dt>
              <dd className="col-sm-9">
                <p>
                  IF YOU HAVE ANY QUESTIONS OR QUERIES ABOUT THIS STATEMENT, OR
                  HOW WE HANDLE YOUR INFORMATION, GET IN TOUCH WITH US
                </p>
              </dd>

              <dt className="col-sm-3">
                WHAT INFORMATION WE HAVE & WHERE WE GET IT:
              </dt>
              <dd className="col-sm-9">
                <p>
                  CONTACT AND BILLING INFORMATION. WHEN YOU CREATE AN ACCOUNT,
                  CREATE A BOOKING OR RESERVATION (RSVP), OR APPLY FOR NIGHTCUBE
                  MEMBERSHIP. ON UPDATED VERSIONS, EXAMPLE ONCE WE ADD
                  TRANSACTION/BILLING LINKS TO OUR PLATFORM, WE MAY COLLECT YOUR
                  CONTACT AND BILLING INFORMATION, SUCH AS YOUR NAME, STREET
                  ADDRESS, ZIP CODE, EMAIL, PHONE NUMBER AND CREDIT CARD NUMBER
                  .
                </p>

                <p>
                  <Link to="#">
                    WARNING : WE DO NOT COLLECT OR STORE CVV CODE TOWARDS YOUR
                    CREDIT OR DEBIT CARD.
                  </Link>
                </p>
              </dd>

              <dt className="col-sm-3">FOR MORE INFORMATION : </dt>
              <dd className="col-sm-9">
                <p>
                  <Link
                    to="https://moneytips.com/credit-card-security/"
                    target="_blank"
                  >
                    HTTPS://WWW.CREDITCARDINSIDER.COM/LEARN/CREDIT-CARD-SECURITY/
                  </Link>
                </p>
                <p>
                  INFORMATION YOU POST. WE MAY COLLECT INFORMATION YOU POST IN A
                  PUBLIC FORUM ON OUR WEBSITE OR ON A 3RD PARTY SOCIAL MEDIA
                  SPACE. DEMOGRAPHIC INFORMATION. WE MIGHT COLLECT INFORMATION
                  LIKE YOUR AGE RANGE, OR GENDER, OR INFORMATION ABOUT EVENTS
                  YOU LIKE OR BOOKINGS YOU MAKE. WE MIGHT COLLECT THIS AS PART
                  OF A SURVEY, FOR EXAMPLE, TO IMPROVE ACCURACY TOWARDS
                  AGGREGATED SOLUTIONS & SERVICES. OTHER INFORMATION. IF YOU USE
                  OUR WEBSITE OR APPS, WE MAY COLLECT INFORMATION ABOUT THE
                  BROWSER AND DEVICE YOU’RE USING, YOUR IP ADDRESS, YOUR
                  LOCATION, THE SITE FROM WHICH YOU ARE REDIRECTED TO THIS SITE,
                  THE SITE TO WHICH YOU ARE REDIRECTED FROM THIS SITE, AND HOW
                  YOU USED OR DIDN’T USE OUR SITE OR APP. WE MAY COLLECT THIS
                  USING TECHNOLOGY SUCH AS GPS AND WI-FI. WE COLLECT INFORMATION
                  IN DIFFERENT WAYS WE COLLECT INFORMATION DIRECTLY FROM YOU.
                  FOR EXAMPLE, IF YOU BUY MEMBERSHIPS, CREATE AN ACCOUNT, OR
                  REGISTER FOR A PROMOTION. WE ALSO COLLECT INFORMATION IF YOU
                  POST A COMMENT ON OUR WEBSITES OR ASK US A QUESTION WE COLLECT
                  INFORMATION FROM YOU PASSIVELY. WE USE TRACKING TOOLS LIKE
                  BROWSER COOKIES AND WEB BEACONS. WE ALSO COLLECT INFORMATION
                  FROM OUR APPS. FOR MORE INFORMATION ABOUT THESE TOOLS AND HOW
                  TO CONTROL THEM :{" "}
                  <Link to="https://www.cerillion.com/legal/cookies-and-web-beacon-policy/">
                    HTTPS://WWW.CERILLION.COM/LEGAL/COOKIES
                  </Link>{" "}
                  WE GET INFORMATION ABOUT YOU FROM 3RD PARTIES. FOR EXAMPLE, IF
                  YOU USE A SOCIAL MEDIA FEATURE WITHIN OUR WEBSITES OR APPS OR
                  POST TO A SOCIAL MEDIA PLATFORM, THE SOCIAL MEDIA SITE WILL
                  GIVE US SOME INFORMATION ABOUT YOU.
                </p>
              </dd>

              <dt className="col-sm-3">HOW WE USE YOUR INFORMATION & WHY</dt>
              <dd className="col-sm-9">
                <p>
                  WE USE INFORMATION AS DISCLOSED AND DESCRIBED HERE WE USE
                  INFORMATION TO PROVIDE YOU WITH SOLUTIONS AND SERVICES. WE USE
                  YOUR INFORMATION TO PROCESS YOUR BOOKINGS, RESERVATIONS OR
                  VALIDATE MEMBERSHIPS AND PROVIDE YOU WITH CUSTOMER ASSISTANCE.
                  THIS INCLUDES SENDING YOU EMAILS ABOUT YOUR ACCOUNT OR A
                  BOOKING, RESERVATION REQUESTS THAT YOU HAVE MADE OR DISCOUNT
                  COUPONS IF YOU ARE A HAVING A MEMBERSHIP WITH US. WE MIGHT
                  ALSO CONTACT YOU ABOUT THIS POLICY OR OUR WEBSITE TERMS &
                  CONDITIONS AS PER YOUR UTILIZATION OF THIS SITE. WE USE
                  INFORMATION TO RESPOND TO YOUR REQUESTS OR QUESTIONS. FOR
                  EXAMPLE, WE MIGHT USE YOUR INFORMATION TO CONFIRM YOUR
                  REGISTRATION FOR AN EVENT OR PROMOTIONS. YOU MAY GIVE US YOUR
                  FRIEND’S INFORMATION, FOR EXAMPLE VIA OUR REFERRAL SERVICE TO
                  TELL A FRIEND ABOUT OUR WEBSITE OR TO PURCHASE A MEMBERSHIP.
                  WE WILL ONLY USE YOUR FRIEND’S INFORMATION TO PROVIDE SERVICES
                  YOU REQUESTED. YOU MAY CONTACT OUR CUSTOMER ASSISTANCE TEAM TO
                  ASK US TO DELETE THEIR INFORMATION. WE USE YOUR INFORMATION TO
                  IMPROVE OUR SOLUTIONS AND SERVICES. WE MIGHT USE YOUR
                  INFORMATION TO CUSTOMIZE YOUR EXPERIENCE WITH US BY ENHANCING
                  ACCURACY OR FEATURES. THIS COULD INCLUDE DISPLAYING EVENTS,
                  ARTISTS, CONTENTS BASED ON YOUR FILTERED PREFERENCES. WE MAY
                  USE YOUR INFORMATION TO MAKE OUR SITE, SOLUTIONS AND SERVICES
                  AVAILABLE AT OUR DISPOSAL BETTER RESPONSIVE TOWARDS YOU. WE
                  MAY COMBINE INFORMATION WE GET FROM YOU WITH INFORMATION ABOUT
                  YOU WE GET FROM 3RD PARTY PLATFORMS, EXAMPLE SOCIAL MEDIA. WE
                  USE INFORMATION FOR SECURITY PURPOSES. WE USE INFORMATION TO
                  PROTECT OUR COMPANY, OUR CUSTOMERS, OUR ENTITIES OR OUR SITES
                  AND ANY OTHER DIGITAL MEDIA PLATFORM OPERATING UNDER US. THIS
                  INCLUDES TO PREVENT ILLEGAL, MANIPULATIVE OR DESTRUCTIVE
                  BEHAVIOR WE USE INFORMATION FOR MARKETING & PROMOTIONAL
                  PURPOSES. FOR EXAMPLE, WE MIGHT SEND YOU INFORMATION ABOUT
                  SPECIAL PROMOTIONS OR OFFERS OR MEMBERSHIP EXPERIENCES YOU
                  MIGHT BE INTERESTED IN. WE MIGHT ALSO TELL YOU ABOUT NEW
                  FEATURES OR SERVICES AS SOON AS THEY ARE UPDATED. THESE MIGHT
                  BE OUR OWN PROGRAMS OR FEATURES, OR 3RD PARTY OFFERS OR
                  SOLUTIONS WE THINK YOU MIGHT FIND INTERESTING. FOR EXAMPLE, IF
                  YOU BUY MEMBERSHIP FROM US WE MAY ENROLL YOU IN OUR
                  NEWSLETTER. WE MAY ALSO USE PUSH NOTIFICATIONS THROUGH OUR
                  SITE. WE MAY USE PUSH NOTIFICATIONS AND YOUR LOCATION
                  INFORMATION IN A COMBINATION TO SEND YOU ALERTS REGARDING
                  LOCAL EVENTS OF YOUR INTEREST. WE USE INFORMATION AS OTHERWISE
                  PERMITTED BY LAW, TOWARDS LAW IF ANY OR AS WE MAY NOTIFY YOU.
                  WE KEEP YOUR INFORMATION AS LONG AS IT IS NECESSARY OR
                  RELEVANT FOR OUR STRUCTURED ORGANIZATION. WE ALSO MAY RETAIN
                  INFORMATION TO RESOLVE DISPUTES, ENFORCE OUR AGREEMENTS AND
                  OTHERWISE REQUIRED BY LAW IF ANY OR DISCARD THEM SECURELY WHEN
                  THE FOLLOWING INFORMATION ARE NO LONGER NEEDED. FOR EXAMPLE,
                  WHEN YOU ARE NO LONGER HOLDING AN ACCOUNT WITH US OR NO LONGER
                  SUBSCRIBED TO OUR NEWSLETTER OR PUSH NOTIFICATION OR
                  COMBINATION OF ALL.
                </p>
              </dd>

              <dt className="col-sm-3">HOW WE USE YOUR INFORMATION & WHY</dt>
              <dd className="col-sm-9">
                <p>
                  WE DO NOT RENT, OUTSOURCE, SELL YOUR INFORMATION TO ANYONE OR
                  ANYWHERE OR 3RD PARTIES WITHOUT YOUR APPROVAL OR PRIOR
                  CONSENT. WE MAY SHARE INFORMATION WITHIN NEROLIFE NETWORKS
                  PVT. LTD. & NEROLIFE GROUP OF COMPANIES. THIS MAY INCLUDE OUR
                  CRM TOOLS - NIGHTCUBE, OUR DEVELOPERS - ADITSHA TECHNOLOGY
                  PVT. LTD., AND PARTNER OUTLETS (FOR EXAMPLE, IF YOU ARE
                  HEADING TOWARDS ANY ENLISTED OUTLET FOR EVENT), AND/OR ANY
                  INHOUSE DEVELOPED API INTEGRATION PLATFORMS FOR EXAMPLE, PHONE
                  MESSAGING SERVICES (PMS), CHAT BOTS & VIRTUAL CUSTOMER
                  ASSISTANCE (ARTIFICIAL INTELLIGENCE BOTS / MACHINE LEARNING
                  DIAGNOSTICS / HUMAN BEHAVIORAL PATTERN RECOGNITIONS) WE MAY
                  SHARE INFORMATION WITH INTEGRATED COMPANIES WHO PERFORM
                  SERVICES ON OUR BEHALF. FOR EXAMPLE, WE SHARE INFORMATION WITH
                  COMPANIES WHO HELP US MANAGE OUR IT INFRASTRUCTURE OR WHO
                  FULFILL YOUR BOOKINGS & RESERVATIONS OR ALLOCATE MEMBERSHIPS
                  AND NEWSLETTERS. SOME VENDORS MAY BE OPERATING OUTSIDE OF
                  BENGALURU, KARNATAKA, INDIA OR INDIA. WE MAY SHARE INFORMATION
                  WITH OUR BUSINESS PARTNERS AS IN PARTNER OUTLETS WHERE EVENTS
                  ARE TAKING PLACE. THIS INCLUDES A PARTNER OUTLET WHO OPERATES
                  A VENUE WHERE WE HOLD EVENTS OR PARTNER OUTLET WHO ORGANIZE
                  AND HOST AN EVENT IN NATURE OF THE ARTIST, PROMOTERS OR TEAM,
                  OR SPONSOR OF AN EVENT. OUR PARTNERS USE THE INFORMATION WE
                  GIVE THEM AS DESCRIBED IN THEIR PRIVACY POLICIES, WHICH MAY
                  INCLUDE SENDING YOU MARKETING MATERIALS & PROMOTIONAL
                  COMMUNICATIONS. YOU SHOULD READ THOSE POLICES TO LEARN HOW
                  THEY TREAT YOUR INFORMATION. WE MAY SHARE INFORMATION IF WE
                  THINK WE HAVE TO IN ORDER TO COMPLY WITH THE LAW OR TO PROTECT
                  OURSELVES. FOR EXAMPLE, WE WILL SHARE INFORMATION TO RESPOND
                  TO A COURT ORDER OR SUBPOENA. WE MAY ALSO SHARE INFORMATION IF
                  A GOVERNMENT AGENCY OR INVESTIGATORY BODY REQUESTS IT. OR, WE
                  MIGHT ALSO SHARE INFORMATION WHEN WE ARE INVESTIGATING
                  POTENTIAL FRAUD TO PREVENT ILLEGAL, MANIPULATIVE OR
                  DESTRUCTIVE BEHAVIOR. WE MAY SHARE INFORMATION WITH ANY
                  SUCCESSOR TO ALL OR PART OF OUR BUSINESS. FOR EXAMPLE, IF PART
                  OF OUR BUSINESS IS SOLD WE MAY GIVE INFORMATION AS PART OF
                  THAT TRANSACTION WE MAY SHARE YOUR INFORMATION FOR REASONS NOT
                  DESCRIBED IN THIS STATEMENT. YOU WILL BE INFORMED BY US AND/OR
                  OUR GOVERNING BODIES BEFORE WE DO SO AS WE ARE BONDED TO APPLY
                  SUCH TRANSACTION ONLY IN ACCORDANCE TO YOUR APPROVAL OR PRIOR
                  CONSENT.
                </p>
              </dd>

              <dt className="col-sm-3">YOUR CHOICES & RIGHTS</dt>
              <dd className="col-sm-9">
                <p>
                  YOU HAVE CERTAIN CHOICES ABOUT HOW WE USE YOUR INFORMATION YOU
                  CAN OPT OUT OF RECEIVING OUR MARKETING OR PROMOTIONAL
                  COMMUNICATIONS. TO STOP RECEIVING OUR PROMOTIONAL EMAILS,
                  FOLLOW THE INSTRUCTIONS IN ANY MARKETING EMAIL YOU GET FROM
                  US. YOU CAN ALSO CHANGE YOUR PREFERENCE SETTINGS IN YOUR
                  ACCOUNT. IT MAY TAKE ABOUT 10 OPERATING DAYS TO PROCESS YOUR
                  REQUEST. EVEN IF YOU OPT OUT OF GETTING MARKETING OR
                  PROMOTIONAL COMMUNICATIONS, WE WILL STILL BE ABLE TO SEND YOU
                  TRANSACTIONAL MESSAGES. FOR EXAMPLE, WE MAY STILL CONTACT YOU
                  ABOUT YOUR BOOKING OR MEMBERSHIP. YOU CAN MODIFY INFORMATION
                  YOU HAVE GIVEN US. TO CORRECT OR DELETE INFORMATION OR UPDATE
                  ACCOUNT SETTINGS, LOG INTO YOUR ACCOUNT AND FOLLOW THE
                  INSTRUCTIONS. WE MAKE CHANGES AS SOON AS WE CAN. THIS
                  INFORMATION MAY STAY IN OUR BACKUP FILES. IF WE CANNOT MAKE
                  THE CHANGES YOU WANT, WE WILL LET YOU KNOW AND EXPLAIN WHY. IF
                  YOU CONTACT US REQUESTING ACCESS TO YOUR INFORMATION, WE WILL
                  RESPOND WITHIN 45 OPERATING DAYS. YOU CAN CONTROL COOKIES AND
                  TRACKING TOOLS. FOR MORE INFORMATION ON HOW TO MANAGE COOKIES
                  AND OTHER TRACKING TOOLS, PLEASE CLICK HERE :
                  <Link to="https://www.cerillion.com/legal/cookies-and-web-beacon-policy/">
                    HTTPS://WWW.CERILLION.COM/LEGAL/COOKIES
                  </Link>{" "}
                  YOU CAN CONTROL TOOLS ON YOUR MOBILE DEVICES. FOR EXAMPLE, YOU
                  CAN TURN OFF THE GPS LOCATOR OR PUSH NOTIFICATIONS ON YOUR
                  DEVICE
                </p>
              </dd>

              <dt className="col-sm-3">PRIVACY LAW OF INDIA</dt>
              <dd className="col-sm-9">
                <p>
                  UNDER THE PERSONAL DATA PROTECTION BILL, 2019 IF YOU ARE A
                  RESIDENT OF INDIA AND HAVE AN ESTABLISHED CONSUMER
                  RELATIONSHIP WITH US, YOU CAN WRITE AN EMAIL TO US REQUESTING
                  A LIST OF THE PERSONAL INFORMATION WE HAVE SHARED WITH 3RD
                  PARTIES & THEIR UTILIZATION PURPOSES. WE WILL ALSO PROVIDE YOU
                  A LIST OF THE 3RD PARTIES THAT HAVE RECEIVED YOUR INFORMATION.
                  YOU CAN MAKE ONE REQUEST EACH YEAR MENTION IN YOUR EMAIL THAT
                  YOU ARE MAKING A “PERSONAL DATA PROTECTION BILL” INQUIRY. WE
                  WILL RESPOND TO SUCH WITHIN 45 DAYS. FOR MORE INFORMATION ON
                  “PERSONAL DATA PROTECTION BILL” PLEASE VISIT :
                  <Link to="https://prsindia.org/billtrack/the-personal-data-protection-bill-2019">
                    HTTPS://WWW.PRSINDIA.ORG/BILLTRACK/PERSONAL-DATA-PROTECTION-BILL-2019
                  </Link>
                  KARNATAKA STATE HUMAN RIGHTS COMMISSION, IF YOU ARE A RESIDENT
                  OF KARNATAKA, YOU HAVE PRIVACY RIGHTS GOVERNED BY THE
                  KARNATAKA STATE HUMAN RIGHTS COMMISSION (KSHRC) UNDER
                  GOVERNMENT OF KARNATAKA (GOK) FOR MORE INFORMATION ON
                  “KARNATAKA STATE HUMAN RIGHTS COMMISSION” PLEASE VISIT :
                  <Link to="https://kshrc.karnataka.gov.in/english">
                    HTTPS://KSHRC.KARNATAKA.GOV.IN/ENGLISH
                  </Link>{" "}
                  YOU MAY SUBMIT A REQUEST TO ENACT ANY OF THE ABOVE RIGHTS BY
                  WRITTEN SUBMISSION THROUGH CUSTOMER ASSISTANCE EMAIL :
                  NEROLIFEEXCLUSIVENETWORKS@GMAIL.COM OR CALLING US
                  (+91)-9740619310. WE MAY REQUIRE ADDITIONAL INFORMATION TO
                  VERIFY YOUR IDENTITY BEFORE RESPONDING TO A KSHRC/GOK REQUEST.
                  WE WILL RESPOND TO YOUR REQUEST WITHIN 45 DAYS IF POSSIBLE AND
                  REQUIRED UNDER THE LAW.
                </p>
              </dd>

              <dt className="col-sm-3">
                PERSONAL INFORMATION COLLECTED ON USERS
              </dt>
              <dd className="col-sm-9">
                <p>
                  NAMES AND ALIASES PHONE NUMBER E-MAIL ADDRESS UNIQUE
                  IDENTIFIERS AGE GROUP IP ADDRESS INTERACTIONS WITH CUSTOMER
                  ASSISTANCE INFORMATION ABOUT TRANSACTIONS MADE ON ALL OF OUR
                  PLATFORMS PERSONAL PREFERENCES AND ATTRIBUTES COOKIES/WEB
                  BEACONS – WE USE TRACKING TOOLS LIKE BROWSER COOKIES AND WEB
                  BEACONS DEVICE ATTRIBUTES – GPS, WI-FI, IP ADDRESS
                </p>
              </dd>

              <dt className="col-sm-3">
                PERSONAL INFORMATION DISCLOSED FOR ANY BUSINESS PURPOSE OR SOLD
                ABOUT USERS
              </dt>
              <dd className="col-sm-9">
                <p>
                  TO CANCEL SHARING OF YOUR PERSONAL INFORMATION FOR OUR SERVICE
                  IMPROVEMENTS, PLEASE SEND “DO NOT SHARE MY PERSONAL
                  INFORMATION” WITH YOUR CUSTOMER ID VIA. EMAIL :
                  NEROLIFEEXCLUSIVENETWORKS@GMAIL.COM TO OUR CUSTOMER ASSISTANCE
                  TEAM OR USE “CONTACT US” OPTIONS PRESENTED ABOVE TO SUBMIT A
                  REQUEST.
                </p>
              </dd>

              <dt className="col-sm-3">SOURCES OF DATA ABOUT USERS:</dt>
              <dd className="col-sm-9">
                <p>
                  SELF-DISCLOSED (EX. INFORMATION PROVIDED WHEN INTERACTING WITH
                  OUR SOLUTIONS AND SERVICES, SITES, ALL DIGITAL PLATFORMS
                  OPERATING UNDER US) BUSINESS PARTNERS (EX. ANALYTICS
                  COMPANIES, CRM SOFTWARE’S EXAMPLE NIGHTCUBE, PROMOTERS,
                  ARTISTS, MEMBERSHIP FORUMS, PARTNER OUTLETS, ETC.) DATA
                  BROKERS (EX. MARKETING COMPANIES, ADVERTISING PARTNERS, PUBLIC
                  FIGURES & INFLUENCERS, SOCIAL MEDIA ETC.) TECHNICAL SERVICE
                  PROVIDERS (EX. CLOUD STORAGE & SERVICE PROVIDERS, IT
                  MAINTENANCE)
                </p>
              </dd>

              <dt className="col-sm-3">SOURCES OF DATA ABOUT USERS:</dt>
              <dd className="col-sm-9">
                <p>
                  PROVIDING SOLUTIONS AND SERVICES EVENT MANAGEMENT MARKET
                  RESEARCH AND PREFERENCE ANALYTICS TO PREVENT, POTENTIAL FRAUD,
                  ILLEGAL, MANIPULATIVE OR DESTRUCTIVE BEHAVIOR MARKETING &
                  PROMOTIONAL MATERIALS CLIENT SERVICES STAFF ADMINISTRATION,
                  TRAINING & GUIDELINES
                </p>
              </dd>

              <dt className="col-sm-3">
                THIRD PARTIES WITH WHOM WE SHARE PERSONAL INFORMATION
              </dt>
              <dd className="col-sm-9">
                <p>
                  BUSINESS PARTNERS (EX. ANALYTICS COMPANIES, CRM SOFTWARE’S
                  EXAMPLE NIGHTCUBE, PROMOTERS, ARTISTS, MEMBERSHIP FORUMS,
                  PARTNER OUTLETS, ETC.) DATA BROKERS (EX. MARKETING COMPANIES,
                  ADVERTISING PARTNERS, PUBLIC FIGURES & INFLUENCERS, SOCIAL
                  MEDIA ETC.) TECHNICAL SERVICE PROVIDERS (EX. CLOUD STORAGE &
                  SERVICE PROVIDERS, IT MAINTENANCE) WE, OUR WEBSITES AND APPS,
                  ENTITIES OPERATING WITH US, ENTITIES OPERATING FOR US, 3RD
                  PARTIES ASSOCIATED, BUSINESS PARTNERS ASSOCIATED DO NOT
                  RESPOND TO “DO NOT TRACK” REQUESTS AS DATA FROM BROWSERS,
                  BROWSER COOKIES OR WEB BEACONS ARE TRACKED BY DEFAULT.
                </p>
              </dd>

              <dt className="col-sm-3">
                OUR SITES AND APPS ARE NOT INTENDED FOR CHILDREN & MINORS
              </dt>
              <dd className="col-sm-9">
                <p>
                  OUR SITES AND APPS ARE MEANT FOR ADULTS. WE DO NOT KNOWINGLY
                  COLLECT PERSONAL INFORMATION FROM CHILDREN UNDER 16. IF YOU
                  ARE A PARENT OR LEGAL GUARDIAN AND THINK YOUR CHILD UNDER 16
                  HAS GIVEN US INFORMATION, YOU CAN EMAIL US. YOU CAN ALSO WRITE
                  TO US AT THE ADDRESS LISTED AT THE END OF THIS POLICY. PLEASE
                  MARK YOUR INQUIRIES “MINOR ACCESS INFORMATION REQUEST”
                </p>
              </dd>

              <dt className="col-sm-3">LOOKING AFTER YOUR INFORMATION</dt>
              <dd className="col-sm-9">
                <p>
                  WE USE STANDARD SECURITY MEASURES WE HAVE SECURITY MEASURES IN
                  PLACE TO PROTECT YOUR INFORMATION. THE STANDARD SECURITY
                  MEASURES WE USE WILL DEPEND ON THE TYPE OF INFORMATION
                  COLLECTED. HOWEVER, THE INTERNET IS NOT 100% SECURE. WE CANNOT
                  PROMISE THAT YOUR USE OF OUR SITES WILL BE COMPLETELY SAFE. IF
                  YOU THINK THAT YOUR ACCOUNT HAS BEEN MANIPULATED, HACKED
                  AND/OR OTHERWISE ALTERED USING YOUR CREDENTIALS, KINDLY
                  CONTACT US AT THE ADDRESS BELOW. WE STORE INFORMATION BOTH
                  INSIDE AND OUTSIDE OF INDIA AND INDIAN PROVINCES IF YOU LIVE
                  OUTSIDE INDIA, YOU UNDERSTAND AND AGREE THAT WE MAY TRANSFER
                  YOUR INFORMATION TO THE LEGAL AUTHORITY & GOVERNMENT BODIES OF
                  INDIA AS PER REQUIREMENT. YOU COMPLY THAT THIS SITE IS SUBJECT
                  TO GOVERNMENT OF INDIA RULES & REGULATIONS, WHICH MAY NOT
                  AFFORD THE SAME LEVEL OF PROTECTION OF THOSE IN YOUR COUNTRY.
                  WE MAY HYPERLINK 3RD PARTY SITES OR SERVICES WE DON’T CONTROL
                  IF YOU CLICK ON ONE OF THOSE LINKS, YOU WILL BE TAKEN TO
                  WEBSITES WE DO NOT CONTROL. THIS STATEMENT DOES NOT APPLY TO
                  THE PRIVACY PRACTICES OF THOSE WEBSITES. READ THE PRIVACY
                  PRACTICES OF OTHER WEBSITES CAREFULLY. WE ARE NOT RESPONSIBLE
                  FOR THESE 3RD PARTY SITES OR THEIR OPERATIONS. OUR SITE MAY
                  ALSO SERVE 3RD PARTY CONTENT WHICH MIGHT CONTAIN 3RD PARTY
                  COOKIES, WEB BEACONS OR OTHER TRACKING TECHNOLOGIES. WE DO NOT
                  CONTROL THE USE OF THOSE TECHNOLOGIES
                </p>
              </dd>

              <dt className="col-sm-3">CONTACT US</dt>
              <dd className="col-sm-9">
                <p>
                  PLEASE CONTACT US IF YOU WANT MORE INFORMATION IF YOU HAVE
                  MORE QUESTIONS & QUERIES ABOUT THIS PRIVACY STATEMENT OR ANY
                  OTHER PRIVACY CONCERNS, YOU CAN WRITE AN EMAIL TO US STATING
                  THE SAME. PLEASE DO NOT INCLUDE YOUR CREDIT CARD NUMBER OR
                  OTHER SENSITIVE INFORMATION IN YOUR EMAIL. YOU CAN WRITE US
                  AT: CUSTOMER ASSISTANCE: NEROLIFEEXCLUSIVENETWORKS@GMAIL.COM
                  NEROLIFE NETWORKS PVT. LTD #17 KIRLOSKAR, 1ST CROSS SAPTAGIRI,
                  BENGALURU 560073, KARNATAKA, INDIA ATTENTION: LEGAL WHAT TO DO
                  IF THERE IS AN UPDATE TO THIS STATEMENT FROM TIME TO TIME WE
                  MAY CHANGE OUR PRIVACY PRACTICES. WE WILL NOTIFY YOU OF ANY
                  MATERIAL CHANGES TO THIS POLICY STATEMENT AS MAY BE REQUIRED
                  BY LAW. WE WILL ALSO POST AN UPDATED COPY ON OUR WEBSITE.
                  PLEASE CHECK OUR SITE PERIODICALLY FOR UPDATES. © 2020
                  NEROLIFE NETWORKS PVT. LTD. ALL RIGHTS RESERVED.
                </p>
              </dd>
            </dl>
          </p>
        </figcaption>
      </figure>
    </div>
  );
};

export default Privacy;
