import React from "react";
import { Link } from "react-router-dom";

const TermsAndConditions = () => {
  return (
    <div>
      <figure class="text-center">
        <blockquote class="blockquote">
          <p className="display-1 m-5">Terms And Conditions.</p>
        </blockquote>
        <figcaption class="blockquote-footer">
          THE FOLLOWING ARE THE TERMS OF USE (“TERMS & CONDITIONS”)
          <p className="m-5">
            THAT GOVERN YOUR USE OF THE WEBSITES AND APPLICATIONS WHERE THIS
            APPEARS (COLLECTIVELY, THE “SITE”). OUR PRIVACY POLICY AND ANY OTHER
            POLICIES, RULES OR GUIDELINES THAT MAY BE APPLICABLE TO PARTICULAR
            OFFERS OR FEATURES ON THE SITE ARE ALSO INCORPORATED INTO THESE
            TERMS & CONDITIONS. BY VISITING OR USING THE SITE, YOU EXPRESSLY
            AGREE TO THESE TERMS & CONDITIONS AS REPRESENTED & AS UPDATED FROM
            TIME TO TIME. WE MAY MAKE CHANGES TO THESE TERMS & CONDITIONS AT ANY
            TIME. ANY CHANGES WE MAKE WILL BE EFFECTIVE IMMEDIATELY WHEN WE POST
            A REVISED VERSION OF THESE TERMS & CONDITIONS ON THE SITE. THE “LAST
            UPDATED” DATE ABOVE WILL TELL YOU WHEN THESE TERMS & CONDITIONS WERE
            LAST REVISED. BY CONTINUING TO USE THIS SITE AFTER THAT DATE, YOU
            AGREE TO THE FOLLOWING CHANGES. WHILE SOME OF THE ITEMS LISTED ON
            THE SITE MAY APPEAL TO CHILDREN, THE SITE IS NOT TARGETED AT
            INDIVIDUAL BELOW THE AGE OF 16, AND THEY ARE NOT PERMITTED TO USE
            THE SITE. WE STRONGLY ENCOURAGE ALL PARENTS AND GUARDIANS TO MONITOR
            THE INTERNET USE BY THEIR CHILDREN. IF YOU USE THE SITE, YOU AFFIRM
            YOU ARE AT LEAST 16+ YEARS OLD
          </p>
          <p className="m-5">
            <dl className="row">
              <dt className="col-sm-3">REGISTERED MEMBERS:</dt>
              <dd className="col-sm-9">
                <p>
                  IF YOU ARE A REGISTERED MEMBER OR CREATE AN ACCOUNT ON THIS
                  SITE YOU AUTOMATICALLY QUALIFY FOR PREMIUM SOLUTIONS AND
                  SERVICES LIKE BOOKINGS, RSVP, NIGHTCUBE STEM SERVICES, FILTERS
                  AVAILABLE AT OUR DISPOSAL HANDCRAFTED ONLY FOR YOU. YOU CAN
                  MAKE BOOKINGS TOWARDS EVENTS OF YOUR PREFERENCE, OR RSVP FOR
                  VIP IN ANY OF THE AVAILABLE PARTNER OUTLETS AS WELL AS AVAIL
                  DISCOUNTS UNDER NIGHTCUBE STEM SERVICE CATEGORY. BOOKINGS ARE
                  ORDERS OR PURCHASES MADE TOWARDS TICKETED EVENTS AND CAN BE
                  AVAILED ONLINE DIRECTLY TOWARDS THE HOSTING OUTLET THROUGH
                  THIS SITE. RSVP FOR VIP IS A SWEAT FREE SERVICE WHICH INFORMS
                  HOSTING OUTLET MANAGEMENT ABOUT YOUR INTEREST IN ATTENDING THE
                  EVENT OR BOOK A TABLE FOR INDIVIDUAL OR GROUPS ONLINE DIRECTLY
                  THROUGH THIS SITE TO AVOID LONG QUEUES ACCESSIBLE FOR A
                  DESIGNATED PERIOD OF TIME. HOSTING OUTLET MANAGEMENT OWNS
                  COMPLETE RIGHTS TOWARDS ACCEPTING YOUR RSVP REQUEST OR
                  DISCARDING OR REPLACE WITH OTHER USERS AS PER ELIGIBILITY
                  CRITERIA OF OUTLET’S RSVP GUIDELINES. NIGHTCUBE STEM PROVIDES
                  HOSTING OUTLET MANAGEMENT WITH INFORMATION ABOUT YOUR
                  MEMBERSHIP ON THIS SITE FOLLOWED BY YOUR CUSTOMER ID WHICH
                  ALLOWS YOU TO TAKE OFFERS & DISCOUNTS ON PURCHASE ORDERS
                  AVAILABLE AT ANY PARTNER OUTLET ENLISTED ON THIS SITE ONCE PER
                  DAY. HIGHER PURCHASE ORDERS RESULTS IN HIGHER REWARDS AND
                  DISCOUNT OFFERS. FOR MORE INFORMATION KINDLY EMAIL OUR
                  CUSTOMER ASSISTANCE :{" "}
                  <span className="text-primary">
                    NEROLIFEEXCLUSIVENETWORKS@GMAIL.COM
                  </span>
                </p>
              </dd>

              <dt className="col-sm-3">CODE OF CONDUCT:</dt>
              <dd className="col-sm-9">
                <p>
                  YOU AGREE THAT YOU WILL COMPLY WITH ALL APPLICABLE LAWS, RULES
                  AND REGULATIONS AS GUIDED, AND THAT YOU SHOULD NOT: RESTRICT
                  OR INHIBIT ANY OTHER PERSON FROM USING THE SITE USE THE SITE
                  FOR ANY ILLEGAL PURPOSES EXPRESS OR IMPLEMENT ANY STATEMENTS
                  YOU MAKE THAT ARE FALSE, NOT ENDORSED OR ENCOURAGED BY US, OR
                  WITHOUT OUR PRIOR WRITTEN CONSENT IMPERSONATE ANY PERSON OR
                  ENTITY, WHETHER REAL OR FICTITIOUS, INCLUDING ANY EMPLOYEE OR
                  REPRESENTATIVE OF OUR COMPANY SUBMIT (A) ANY CONTENT OR
                  INFORMATION THAT IS ILLEGAL, FRAUDULENT, LIBELOUS, DEFAMATORY,
                  OR OTHERWISE OBJECTIONABLE, OR INFRINGES OUR OR ANY 3RD
                  PARTY’S INTELLECTUAL PROPERTY OR OTHER RIGHTS; (B) ANY
                  NON-PUBLIC INFORMATION ABOUT COMPANIES WITHOUT AUTHORIZATION;
                  (C) ANY ADVERTISEMENTS, SOLICITATIONS, CHAIN LETTERS, PYRAMID
                  SCHEMES, SURVEYS, CONTESTS, INVESTMENT OPPORTUNITIES OR OTHER
                  UNSOLICITED ALLOCATIONS OR COMMERCIAL COMMUNICATION SUBMIT, OR
                  PROVIDE LINKS TO, ANY POSTINGS CONTAINING MATERIAL THAT COULD
                  BE CONSIDERED HARMFUL, OBSCENE, PORNOGRAPHIC, SEXUALLY
                  EXPLICIT, INDECENT, LEWD, VIOLENT, ABUSIVE, PROFANE,
                  INSULTING, THREATENING, HARASSING, HATEFUL OR OTHERWISE
                  OBJECTIONABLE, INCLUDES THE IMAGE OR LIKENESS OF INDIVIDUALS
                  UNDER 16 YEARS OF AGE, THAT ENCOURAGES OR OTHERWISE DEPICTS OR
                  GLAMORIZES DRUG USE (INCLUDING ALCOHOL AND CIGARETTES),
                  CHARACTERIZES VIOLENCE AS ACCEPTABLE, GLAMOROUS OR DESIRABLE,
                  OR CONTAINS ANY PERSONAL CONTACT INFORMATION OR OTHER PERSONAL
                  INFORMATION IDENTIFYING ANY 3RD PARTY SUBMIT, OR PROVIDE LINKS
                  TO, ANY POSTINGS CONTAINING MATERIAL THAT HARASSES,
                  VICTIMIZES, DEGRADES, OR INTIMIDATES AN INDIVIDUAL OR GROUP OF
                  INDIVIDUALS ON THE BASIS OF RELIGION, RACE, ETHNICITY, SEXUAL
                  ORIENTATION, GENDER, AGE, NATURALLY GIFTED, ACCIDENTAL OR
                  ABILITY ENGAGE IN SPAMMING OR FLOODING HARVEST OR COLLECT
                  INFORMATION ABOUT SITE USERS USE ANY PASSWORD OR CODE TO
                  PARTICIPATE IN A PRESALE OR OTHER OFFER ON THE SITE IF YOU DID
                  NOT RECEIVE THE PASSWORD OR CODE FROM US OR IF YOU VIOLATE THE
                  TERMS & CONDITIONS AS REPRESENTED OF THE PRESALE OR FOLLOWING
                  OFFER USE ANY AREA OF THE SITE FOR COMMERCIAL PURPOSES, SUCH
                  AS TO CONDUCT SALES, PRODUCTS OR SERVICES.
                </p>
              </dd>

              <dt className="col-sm-3">
                OWNERSHIP OF CONTENT AND GRANT OF CONDITIONAL LICENSE:
              </dt>
              <dd className="col-sm-9">
                <p>
                  THE SITE AND ALL DATA, TEXT, DESIGNS, PAGES, PRINT SCREENS,
                  IMAGES, ARTWORK, PHOTOGRAPHS, AUDIO AND VIDEO CLIPS, AND HTML
                  CODE, SOURCE CODE, OR EXISTING SOFTWARE VIEWABLE OR OTHERWISE
                  DISCOVERABLE ON THE SITE (COLLECTIVELY, THE “CONTENT”) ARE
                  OWNED BY NEROLIFE NETWORKS PVT. LTD. OR OUR LICENSORS. WE OWN
                  A COPYRIGHT AND, IN MANY INSTANCES, PATENTS AND OTHER
                  INTELLECTUAL PROPERTY IN THE SITE AND CONTENT. WE MAY CHANGE
                  THE CONTENT AND FEATURES OF THE SITE AT ANY TIME. WE GRANT YOU
                  A LIMITED, CONDITIONAL, NO-COST, NON-EXCLUSIVE,
                  NON-TRANSFERABLE, NON-SUBLICENSABLE LICENSE TO VIEW THIS SITE
                  AND ITS CONTENT AS PERMITTED BY THESE TERMS & CONDITIONS AS
                  REPRESENTED FOR NON-COMMERCIAL PURPOSES ONLY IF YOU ARE A
                  REGISTERED MEMBER AND HOLDING AN ACCOUNT ON THIS SITE, AS A
                  CONDITION PRECEDENT, YOU AGREE THAT YOU WILL NOT: SUBMIT ANY
                  SOFTWARE OR OTHER MATERIALS THAT CONTAIN ANY VIRUSES, WORMS,
                  TROJAN HORSES, DEFECTS, DATE BOMBS, TIME TRAPS OR ANY OTHER
                  ITEMS OF DESTRUCTIVE NATURE MANIPULATE IDENTIFIERS, INCLUDING
                  BY FORGING HEADERS, IN ORDER TO DISGUISE THE ORIGIN OF ANY
                  POSTING THAT YOU SUBMIT LINK TO ANY PORTION OF THE SITE OTHER
                  THAN THE URL ASSIGNED TO THE HOME PAGE OF THE SITE “FRAME” OR
                  “MIRROR IMAGE” ANY PART OF THE SITE MODIFY, ADAPT,
                  SUB-LICENSE, TRANSLATE, SELL, REVERSE ENGINEER, DECOMPILE OR
                  DISASSEMBLE ANY PORTION OF THE SITE OR OTHERWISE ATTEMPT TO
                  DERIVE ANY SOURCE CODE OR UNDERLYING IDEAS OR ALGORITHMS OF
                  ANY PART OF THE CONTENT DEVELOPED BY NEROLIFE NETWORKS OR ANY
                  OF OUR LICENSED 3RD PARTY PARTNERS REMOVE ANY COPYRIGHT,
                  TRADEMARK, WATERMARKS OR OTHER PROPRIETARY RIGHTS NOTICES
                  CONTAINED ON THE SITE USE ANY ROBOT, DIGITAL SPIDER, OFFLINE
                  READER, SITE SEARCH/RETRIEVAL APPLICATION OR OTHER MANUAL OR
                  AUTOMATIC DEVICE, TOOL, OR PROCESS TO RETRIEVE, INDEX, DATA
                  MINE OR IN ANY WAY REPRODUCE OR CIRCUMVENT THE NAVIGATIONAL
                  STRUCTURE OR PRESENTATION OF THE CONTENT OR THE SITE,
                  INCLUDING WITH RESPECT TO ANY CAPTCHA DISPLAYED ON THE SITE.
                  OPERATORS OF PUBLIC SEARCH ENGINES MAY USE SPIDERS TO COPY
                  MATERIALS FROM THE SITE ONLY UPON PRIOR INFORMATION AND
                  WRITTEN CONTEXT FROM US SITE FOR THE SOLE PURPOSE OF AND
                  SOLELY TO THE EXTENT NECESSARY FOR CREATING PUBLICLY AVAILABLE
                  SEARCHABLE INDICES OF THE MATERIALS, BUT NOT CACHES OR
                  ARCHIVES OF SUCH MATERIALS. WE MAY REVOKE THIS EXCEPTION AT
                  ANY TIME AND REQUIRE REMOVAL OF ARCHIVED MATERIALS GATHERED IN
                  THE PAST AS NECESSARY. USE ANY AUTOMATED SOFTWARE OR COMPUTER
                  SYSTEM TO SEARCH FOR, RESERVE, BUY OR OTHERWISE OBTAIN
                  DISCOUNT CODES, PROMOTIONAL CODES, VOUCHERS, GIFT CARDS OR ANY
                  OTHER ITEMS AVAILABLE ON THE SITE, INCLUDING SENDING
                  INFORMATION FROM YOUR COMPUTER TO ANOTHER COMPUTER WHERE SUCH
                  SOFTWARE OR SYSTEM IS ACTIVE. TAKE ANY ACTION THAT IMPOSES OR
                  MAY IMPOSE (IN OUR SOLE DISCRETION) AN UNREASONABLE OR
                  DISPROPORTIONATELY LARGE LOAD ON OUR INFRASTRUCTURE AS WELL AS
                  ACTIVE SERVERS. ACCESS, RELOAD OR REFRESH TRANSACTIONAL PAGES,
                  OR MAKE ANY OTHER REQUEST TO TRANSACTIONAL SERVERS, MORE THAN
                  ONCE DURING ANY THREE-SECOND INTERVAL REQUEST MORE THAN
                  DEFAULT ACCESSIBLE PAGES OF THE SITE IN ANY 24-HOUR PERIOD,
                  WHETHER ALONE OR WITH A GROUP OF INDIVIDUALS MAKE MORE THAN
                  DEFAULT ACCESSIBLE RESERVE REQUESTS ON THE SITE IN ANY 24-HOUR
                  PERIOD, WHETHER ALONE OR WITH A GROUP OF INDIVIDUALS
                  REPRODUCE, MODIFY, DISPLAY, PUBLICLY PERFORM, DISTRIBUTE OR
                  CREATE DERIVATIVE WORKS OF THE SITE OR THE CONTENT USE THE
                  SITE OR THE CONTENT IN AN ATTEMPT TO, OR IN CONJUNCTION WITH,
                  ANY DEVICE, PROGRAM OR SERVICE DESIGNED TO CIRCUMVENT ANY
                  TECHNOLOGICAL MEASURE THAT EFFECTIVELY CONTROLS ACCESS TO, OR
                  THE RIGHTS IN, THE SITE, SYSTEM AND ACTIVE SERVERS. SITE
                  AND/OR CONTENT IN ANY WAY INCLUDING, WITHOUT LIMITATION, BY
                  MANUAL OR AUTOMATIC DEVICE OR PROCESS, FOR ANY PURPOSE. THIS
                  LICENSE IS EXPRESSLY CONDITIONED ON YOUR PREEXISTING AGREEMENT
                  TO COMPLY WITH, AND YOUR ACTUAL COMPLIANCE WITH, EACH OF THE
                  PROVISIONS DESCRIBED IN THIS OWNERSHIP OF CONTENT AND GRANT OF
                  CONDITIONAL LICENSE SECTION. THIS LICENSE EXISTS ONLY SO LONG
                  AS YOU STRICTLY COMPLY WITH EACH OF THE PROVISIONS DESCRIBED
                  IN THIS SECTION. ANY USE OF THE SITE OR CONTENT BY YOU OR
                  ANYONE ACTING ON YOUR BEHALF THAT DOES NOT STRICTLY COMPLY
                  WITH EACH AND EVERY PROVISION IN THIS SECTION OR EXCEEDS THE
                  SCOPE OF THE LICENSE GRANTED TO YOU HEREIN, CONSTITUTES
                  UNAUTHORIZED REPRODUCTION, DISPLAY, OR CREATION OF
                  UNAUTHORIZED DERIVATIVE VERSIONS OF THE SITE AND CONTENT, AND
                  INFRINGES OUR COPYRIGHTS, TRADEMARKS, PATENTS AND OTHER RIGHTS
                  IN THE SITE AND CONTENT MAY LEAD TO LEGAL ACTIONS. YOU WILL
                  NOT ACQUIRE ANY OWNERSHIP RIGHTS BY USING THE SITE OR THE
                  CONTENT. THE REGISTERED AND UNREGISTERED TRADEMARKS, LOGOS AND
                  SERVICE MARKS, WATERMARKS DISPLAYED ON THE SITE ARE OWNED BY
                  US OR OUR LICENSORS. YOU MAY NOT USE OUR TRADEMARKS, LOGOS AND
                  SERVICE MARKS IN ANY WAY WITHOUT OUR PRIOR WRITTEN PERMISSION.
                  <br />
                  <b>
                    YOU MAY INQUIRE ABOUT OBTAINING PERMISSION BY WRITING US :
                  </b>
                  <br />
                  <b>BUSINESS :</b>
                  <span className="text-primary">
                    SALES@NEROLIFENETWORKS.COM
                  </span>{" "}
                  <br /> <b>CUSTOMER ASSISTANCE :</b>
                  <span className="text-primary">
                    NEROLIFEEXCLUSIVENETWORKS@GMAIL.COM NEROLIFE NETWORKS PVT.
                    LTD.
                  </span>
                  <br /> #17 KIRLOSKAR, 1ST CROSS, SAPTAGIRI, BENGALURU,
                  KARNATAKA 560073, INDIA
                </p>
              </dd>

              <dt className="col-sm-3">FORUMS AND USER CONTENT:</dt>
              <dd className="col-sm-9">
                <p>
                  WE MAY HOST FAN POLLS, MESSAGE BOARDS, BLOG FEEDS, SOCIAL
                  MEDIA REVIEWS AND OTHER FORUMS FOUND ON THE SITE
                  (COLLECTIVELY, “FORUMS”), AND YOU MAY BE ABLE TO SUBMIT
                  SUGGESTIONS, FEEDBACKS, CONCEPTS, AUDIO AND VIDEO RECORDINGS,
                  PHOTOGRAPHS, ARTWORK OR OTHER MATERIALS TO THE FORUMS OR OTHER
                  AREAS OF THE SITE (“USER CONTENT”). BY SUBMITTING USER
                  CONTENT, YOU CERTIFY THAT YOU ARE AT LEAST 16+ YEARS OLD, OR
                  HAVE OBTAINED YOUR PARENT’S OR LEGAL GUARDIAN’S EXPRESS
                  CONSENT TO SUBMIT USER CONTENT YOU OWN ALL RIGHTS TO YOUR USER
                  CONTENT. IF YOU SUBMIT USER CONTENT TO THE SITE, YOU GRANT US
                  A GLOBAL, NON-EXCLUSIVE, TRANSFERABLE, SUBLICENSABLE,
                  ROYALTY-FREE RIGHT AND LICENSE TO USE, REPRODUCE, MODIFY,
                  CREATE DERIVATIVE WORKS OF, DISTRIBUTE, PUBLICLY PERFORM,
                  DISPLAY, ARCHIVE AND COMMERCIALIZE YOUR USER CONTENT, IN OUR
                  SOLE DISCRETION, IN ALL FORMATS AND IN ALL MEDIA CHANNELS NOW
                  KNOWN OR HEREINAFTER DISCOVERED, WITHOUT ANY COMPENSATION OR
                  ACKNOWLEDGMENT TO YOU OR ANYONE ELSE. THIS LICENSE WILL NOT
                  AFFECT YOUR OWNERSHIP IN YOUR USER CONTENT, INCLUDING THE
                  RIGHT TO GRANT ADDITIONAL LICENSES TO YOUR USER CONTENT,
                  EXCEPT IF IT CONFLICTS WITH THESE TERMS & CONDITIONS AS
                  REPRESENTED. WE ARE NOT OBLIGATED TO POST, DISPLAY OR
                  OTHERWISE USE ANY USER CONTENT, OR TO ATTRIBUTE YOUR USER
                  CONTENT TO YOU. YOU WILL NOT MAKE OR AUTHORIZE ANY CLAIM
                  AGAINST US THAT OUR USE OF YOUR USER CONTENT INFRINGES ANY OF
                  YOUR RIGHTS. STATEMENTS, OPINIONS AND REVIEWS POSTED BY
                  PARTICIPANTS & OTHER USERS IN A FORUM MAY BE INACCURATE,
                  OFFENSIVE, OBSCENE, THREATENING OR HARASSING. WE DO NOT
                  ENDORSE OR ENCOURAGE SUCH INFORMATION AND ARE NOT RESPONSIBLE
                  FOR THOSE POSTINGS. WE WILL NOT BE LIABLE FOR ANY LOSS OR HARM
                  CAUSED BY THE POSTING OF OTHER USERS OR YOUR RELIANCE ON
                  INFORMATION OBTAINED THROUGH THE POSTINGS BY OTHER USERS. YOU
                  WILL BE RESPONSIBLE FOR YOUR “ USER CONTENT “ AND THE
                  CONSEQUENCES OF POSTING IT. BY SUBMITTING USER CONTENT, YOU
                  REPRESENT TO US THAT (A) YOU OWN, OR HAVE THE NECESSARY
                  PERMISSION TO SUBMIT THE USER CONTENT AND TO GRANT THE
                  LICENSES TO US UNDER THIS SECTION, (B) YOU HAVE THE WRITTEN
                  PERMISSION OF EVERY IDENTIFIABLE PERSON IN THE USER CONTENT TO
                  USE THAT PERSON’S NAME AND LIKENESS IN THE MANNER CONTEMPLATED
                  BY THE SITE AND THESE TERMS & CONDITIONS AS REPRESENTED OR, IF
                  THE PERSON IS A MINOR, THE WRITTEN PERMISSION OF THE MINOR’S
                  PARENT OR LEGAL GUARDIAN WE WILL HAVE THE RIGHT (BUT NOT THE
                  OBLIGATION) TO MONITOR THE SITE, THE FORUMS AND THE USER
                  CONTENT, AND TO DISCLOSE ANY USER CONTENT AND THE
                  CIRCUMSTANCES SURROUNDING ITS SUBMISSION IN ORDER TO OPERATE
                  THE SITE PROPERLY, OR TO PROTECT OURSELVES, OUR SPONSORS AND
                  OUR USERS, OR TO COMPLY WITH LEGAL OBLIGATIONS OR GOVERNMENT
                  REQUESTS, IF ANY. IF WE ARE NOTIFIED THAT YOUR “ USER CONTENT
                  “ DOES NOT COMPLY WITH THESE TERMS & CONDITIONS AS
                  REPRESENTED, WE MAY INITIATE INVESTIGATION TOWARDS THE
                  ALLEGATION AND MAY DECIDE TO REMOVE YOUR USER CONTENT AND
                  CANCEL YOUR ACCOUNT UPON VALIDATION. WE MAY ALSO HOLD YOU
                  LIABLE FOR ANY USER CONTENT THAT INFRINGES THE RIGHTS OF A 3RD
                  PARTY, AND REQUIRE YOU TO PAY OR REIMBURSE US FOR ANY AMOUNTS
                  WE BELIEVE ARE NECESSARY TO RESOLVE ANY COMPLAINT ARISE DUE TO
                  INCONVENIENCE.
                </p>
              </dd>

              <dt className="col-sm-3">BOOKINGS & RSVP : TERMS SHEET</dt>
              <dd className="col-sm-9">
                <p>
                  WE LOVE YOU
                  <br />
                  PURCHASE OR USE OF ANY BOOKINGS & RSVP CONSTITUTES ACCEPTANCE
                  OF THE FOLLOWING TERMS, AS WELL AS THE TERMS SHEET OF THE
                  SALE, AS ACKNOWLEDGED DURING THE PURCHASE PROCESS. THIS
                  BOOKING IS A REVOCABLE LICENSE FOR THE DATE AND TIME (UNLESS
                  RESCHEDULED) LISTED ON THE FRONT THEREOF. ENTRY INTO THE EVENT
                  IS STRICTLY LIMITED TO PEOPLE WHO ARE “REGISTERED MEMBERS“
                  UNDER NEROLIFE NETWORKS PVT. LTD. AND WHO ARE OVER LEGAL
                  DRINKING AGE AS PER DESIGNATED BY GOVERNMENT OF INDIA NEROLIFE
                  OR ENTITLED VENUE RESERVES THE RIGHT, WITHOUT THE REFUND OF
                  ANY PORTION OF THE BOOKING PURCHASE PRICE, RSVP TO REFUSE
                  ADMISSION OR TO EJECT ANY PERSON WHOSE CONDUCT IS DEEMED
                  TOWARDS NEROLIFE OR ENTITLED VENUE TO BE DISORDERLY, WHO USES
                  VULGAR OR ABUSIVE LANGUAGE, OR WHO FAILS TO COMPLY WITH THE
                  RULES OF THE EVENT ADMISSION. UNAUTHORIZED RESALE OR ATTEMPTED
                  RESALE IS GROUNDS FOR SEIZURE AND CANCELLATION WITHOUT
                  COMPENSATION. BOOKINGS OR RSVP OBTAINED FROM UNAUTHORIZED
                  SOURCES MAY BE LOST, STOLEN OR COUNTERFEIT, AND IF SO ARE
                  VOID. RECORDING AND TRANSMITTING ANY REPORT, PICTURE OR
                  REPRODUCTION OF THE EVENT TO WHICH THE BOOKING OR RSVP IS
                  ISSUED FOR IS UNAUTHORIZED, EXCEPT FOR LIMITED NON-COMMERCIAL
                  PURPOSES ON RESPECTIVE INDIVIDUAL’S PERSONAL SOCIAL MEDIA
                  CHANNELS ONLY PROVIDED THAT RESPECTIVE INDIVIDUAL IS SOLELY
                  RESPONSIBLE FOR AND REQUIRED TO OBTAIN ANY AND ALL PERMISSIONS
                  REQUIRED PRIOR TO POSTING, INCLUDING BUT NOT LIMITED TO MUSIC
                  CLEARANCES, AND THAT RECORDING OR TRANSMITTING ANY VIDEO IN
                  EXCESS OF FIFTEEN (15) SECONDS LONG (REGARDLESS OF WHETHER IT
                  IS A SINGLE VIDEO OR SERIES) IS STRICTLY PROHIBITED.
                  RESPECTIVE INDIVIDUAL ACKNOWLEDGES THAT THE EVENT MAY BE
                  BROADCAST OR OTHERWISE PUBLICIZED, AND HEREBY GRANTS
                  PERMISSION TO UTILIZE RESPECTIVE INDIVIDUAL’S IMAGE OR
                  LIKENESS IN CONNECTION WITH ANY LIVE OR RECORDED TRANSMISSION
                  OR REPRODUCTION OF SUCH EVENT. RESPECTIVE INDIVIDUAL SHOULD
                  NOT BRING ALCOHOLIC BEVERAGES, ILLEGAL DRUGS, CONTROLLED
                  SUBSTANCES, CAMERAS, RECORDING DEVICES, LASER POINTERS, STROBE
                  LIGHTS, IRRITANTS (E.G., ARTIFICIAL NOISEMAKERS), BUNDLES AND
                  CONTAINERS OF ANY KIND INTO THE ENTITLED VENUE PREMISES.
                  BOOKING OR RSVP, IF PRINTED, CANNOT BE REPLACED IF LOST,
                  STOLEN OR DESTROYED, AND IS VALID ONLY FOR THE PARTICULAR
                  EVENT FOR WHICH IT IS ISSUED
                  <br />
                  ANY BOOKING OR RSVP IS NOT TRANSFERABLE OR REDEEMABLE FOR
                  CASH.
                  <br />
                  IT IS AGAINST THE LAW TO REPRODUCE THIS BOOKING OR RSVP IN ANY
                  FORM. PRICE INCLUDES ALL APPLICABLE TAXES. RESPECTIVE
                  INDIVIDUAL ASSUMES ALL RISKS AND DANGER INCIDENTAL TO THE
                  EVENT FOR WHICH THIS BOOKING OR RSVP WAS ISSUED, WHETHER
                  OCCURRING PRIOR TO, DURING, OR AFTER THE EVENT, AND RESPECTIVE
                  INDIVIDUAL VOLUNTARILY AGREES THAT THE MANAGEMENT,
                  VENUE/FACILITY, ARTIST(S) PERFORMING, PARTICIPANTS,
                  PARTICIPATING CLUBS, NEROLIFE NETWORKS PVT. LTD. AND ALL OF
                  THEIR RESPECTIVE PARENTS, SUBSIDIARIES, AFFILIATES, AND THEIR
                  RESPECTIVE OFFICERS, DIRECTORS, OWNERS, EMPLOYEES, AGENTS AND
                  REPRESENTATIVES ARE EXPRESSLY RELEASED FROM ANY CLAIMS ARISING
                  FROM SUCH CAUSES. PLEASE RESPECT THE VENUE AND THE ENVIRONMENT
                  AND AVOID LITTER
                  <br /> <br />
                  <h5 className="text-primary">
                    WARNING: EXCESSIVE EXPOSURE TO LOUD MUSIC WILL DAMAGE YOUR
                    HEARING.
                  </h5>
                  <br /> <br />
                  NEROLIFE NETWORKS PVT. LTD. WILL NOT BE HELD LIABLE FOR
                  AMENITIES PROMISED UNDER VIP SECTION OR OTHERWISE. THE USE OF
                  BOOKING OR RSVP TOWARDS ADVERTISING, PROMOTIONS, CONTESTS,
                  SWEEPSTAKES, GIVEAWAYS, ETC. WITHOUT THE EXPRESS WRITTEN
                  CONSENT OF NEROLIFE NETWORKS IS EXPRESSLY PROHIBITED.
                  RESPECTIVE INDIVIDUAL BEARS ALL RISKS OF INCLEMENT WEATHER.
                  EVENT DATE, TIME, LOCATION AND TALENT SUBJECT TO CHANGE. NO
                  REFUNDS OR EXCHANGES. ALL SALES ARE FINAL.
                  <br />
                  IN THE EVENT OF ANY INCONSISTENCY OR CONFLICT BETWEEN THE TERM
                  SHEET STATED HEREIN AND THE TERMS & CONDITIONS CONTAINED IN
                  THE APPLICABLE THROUGH 3RD PARTY RESELLER TERMS OF USE/SALE,
                  THE TERMS SHEET MAINTAINED HEREIN SHALL CONTROL. NEROLIFE
                  LOVES YOU & REMEMBER, THE MOST CELEBRATED PERSON AMONGST US IS
                  YOU!
                </p>
              </dd>

              <dt className="col-sm-3">
                CLAIMS OF COPYRIGHT INFRINGEMENT ON THE SITE:
              </dt>
              <dd className="col-sm-9">
                <p>
                  UNDER THE MINISTRY OF CORPORATE AFFAIRS SUB-SECTION (2) OF
                  SECTION 7 OF THE COMPANIES ACT, 2013 (18 OF 2013) AND RULE 18
                  OF THE COMPANIES (INCORPORATION) RULES, 2014 UNDER THE
                  GOVERNMENT OF INDIA IF YOU BELIEVE IN GOOD FAITH THAT ANY
                  CONTENT ON THE SITE INFRINGES YOUR COPYRIGHT, YOU MAY SEND US
                  A NOTICE REQUESTING THAT THE CONTENT BE REMOVED THE NOTICE
                  MUST INCLUDE: (A) YOUR (OR YOUR AGENT’S) PHYSICAL OR
                  ELECTRONIC SIGNATURE; (B) IDENTIFICATION OF THE COPYRIGHTED
                  WORK ON OUR SITE THAT IS CLAIMED TO HAVE BEEN INFRINGED (OR A
                  REPRESENTATIVE LIST IF MULTIPLE COPYRIGHTED WORKS ARE INCLUDED
                  IN ONE NOTIFICATION); (C) IDENTIFICATION OF THE CONTENT THAT
                  IS CLAIMED TO BE INFRINGING OR THE SUBJECT OF INFRINGING
                  ACTIVITY, INCLUDING INFORMATION REASONABLY SUFFICIENT TO ALLOW
                  US TO LOCATE THE CONTENT ON THE SITE; (D) YOUR NAME, ADDRESS,
                  TELEPHONE NUMBER AND EMAIL ADDRESS (IF AVAILABLE); (E) A
                  STATEMENT THAT YOU HAVE A GOOD FAITH BELIEF THAT USE OF THE
                  CONTENT IN THE MANNER COMPLAINED OF IS NOT AUTHORIZED BY YOU
                  OR YOUR AGENT OR THE LAW; (F) A STATEMENT THAT THE INFORMATION
                  IN THE NOTIFICATION IS ACCURATE AND, UNDER PENALTY OF PERJURY,
                  THAT YOU OR YOUR AGENT IS AUTHORIZED TO ACT ON BEHALF OF THE
                  COPYRIGHT OWNER. IF YOU BELIEVE IN GOOD FAITH THAT A NOTICE OF
                  COPYRIGHT INFRINGEMENT HAS BEEN WRONGLY FILED AGAINST YOU, YOU
                  MAY SEND US A COUNTER-NOTICE. NOTICES AND COUNTER-NOTICES
                  SHOULD BE SENT THROUGH LEGAL TO, NEROLIFE NETWORKS PVT. LTD.,
                  #17 KIRLOSKAR, 1ST CROSS, SAPTAGIRI, BENGALURU, KA 560073.
                  THERE CAN BE PENALTIES FOR FALSE CLAIMS IF FOUND UNDER THE
                  MINISTRY OF CORPORATE AFFAIRS UNDER THE SUB-SECTION (2) OF
                  SECTION 7 OF THE COMPANIES ACT, 2013 (18 OF 2013) AND RULE 18
                  OF THE COMPANIES (INCORPORATION) RULES, 2014 UNDER THE
                  GOVERNMENT OF INDIA. WE SUGGEST THAT YOU CONSULT YOUR LEGAL
                  ADVISOR BEFORE FILING A NOTICE OR COUNTER-NOTICE. IT IS OUR
                  POLICY TO TERMINATE, IN APPROPRIATE CIRCUMSTANCES, THE ACCESS
                  RIGHTS TO THE SITE OF REPEAT INFRINGERS.
                </p>
              </dd>

              <dt className="col-sm-3">LINKS:</dt>
              <dd className="col-sm-9">
                <p>
                  THE SITE MAY CONTAIN LINKS TO OTHER WEBSITES THAT MAY NOT BE
                  OWNED OR OPERATED BY US. THE FACT THAT WE MAY LINK TO THOSE
                  WEBSITES DOES NOT INDICATE ANY APPROVAL OR ENDORSEMENT OR
                  ENCOURAGEMENT TOWARDS THOSE WEBSITES. WE HAVE NO CONTROL OVER
                  THOSE WEBSITES. WE ARE NOT RESPONSIBLE FOR THE CONTENT OF
                  THOSE WEBSITES, OR THE PRIVACY PRACTICES OF THOSE WEBSITES. WE
                  STRONGLY ENCOURAGE YOU TO BECOME FAMILIAR WITH THE TERMS &
                  CONDITIONS OF USAGE AND PRACTICES OF ANY LINKED WEBSITE. YOUR
                  USE OF OTHER WEBSITES IS AT YOUR OWN RISK AND IS SUBJECT TO
                  THE TERMS & CONDITIONS OF THOSE WEBSITES. IT IS UP TO YOU TO
                  TAKE PRECAUTIONS TO ENSURE THAT WHATEVER LINKS YOU SELECT OR
                  SOFTWARE YOU DOWNLOAD (WHETHER FROM THE SITE OR OTHER SITES)
                  IS FREE OF VIRUSES, WORMS, TROJAN HORSES, DEFECTS, DATE BOMBS,
                  TIME TRAPS AND OTHER ITEMS OF A DESTRUCTIVE NATURE.
                </p>
              </dd>

              <dt className="col-sm-3">PARENTAL CONTROLS:</dt>
              <dd className="col-sm-9">
                <p>
                  YOU CAN BROWSE THE SITE WITHOUT REGISTERING FOR AN ACCOUNT. WE
                  CANNOT PROHIBIT MINORS FROM VISITING OUR SITE, AND MUST RELY
                  ON PARENTS AND GUARDIANS TO DECIDE WHAT MATERIALS ARE
                  APPROPRIATE FOR CHILDREN TO VIEW AND PURCHASE. THERE ARE
                  PARENTAL CONTROL PROTECTIONS (SUCH AS COMPUTER HARDWARE,
                  SOFTWARE OR FILTERING SERVICES) AVAILABLE THAT MAY ASSIST YOU
                  IN LIMITING ACCESS TO MATERIAL THAT IS HARMFUL TO MINORS. WE
                  DO NOT ENDORSE OR ENCOURAGE THE PRODUCTS OR SERVICES LISTED AT
                  THE REFERRED WEBSITE.
                  <br />
                  <Link to="https://in.pcmag.com/parental-control-monitoring/90793/the-best-parental-control-software-for-2020">
                    HTTPS://IN.PCMAG.COM/PARENTAL-CONTROL-MONITORING/90793/THE-BEST-PARENTAL-CONTROL-SOFTWARE-FOR-2020
                  </Link>
                </p>
              </dd>

              <dt className="col-sm-3">ACCESS FROM OUTSIDE INDIA:</dt>
              <dd className="col-sm-9">
                <p>
                  THE SITE IS MOSTLY DIRECTED TO PEOPLE RESIDING IN INDIA. WE DO
                  NOT REPRESENT THAT CONTENT AVAILABLE ON OR THROUGH THE SITE IS
                  APPROPRIATE OR AVAILABLE IN OTHER COUNTRIES & NEROLIFE
                  NETWORKS HAVE NO LEGAL AUTHORIZATION TOWARDS ACCESSIBILITY
                  FROM LOCATIONS OUTSIDE INDIA . WE MAY LIMIT THE AVAILABILITY
                  OF THE SITE OR ANY SERVICE OR PRODUCT DESCRIBED ON THE SITE TO
                  ANY PERSON OR GEOGRAPHIC AREA AT ANY TIME. IF YOU CHOOSE TO
                  ACCESS THE SITE FROM OUTSIDE INDIA, YOU ARE RESPONSIBLE FOR
                  SITE VISIT AT YOUR OWN RISK.
                </p>
              </dd>

              <dt className="col-sm-3">
                RULES FOR SWEEPSTAKES, CONTESTS AND GAMES:
              </dt>
              <dd className="col-sm-9">
                <p>
                  IN ADDITION TO THESE TERMS & CONDITIONS AS REPRESENTED,
                  SWEEPSTAKES, CONTESTS, GAMES OR OTHER PROMOTIONS
                  (COLLECTIVELY, “PROMOTIONS”) MADE AVAILABLE THROUGH THE SITE
                  MAY HAVE SPECIFIC RULES THAT ARE DIFFERENT FROM THESE TERMS &
                  CONDITIONS. BY PARTICIPATING IN A PROMOTION, YOU WILL BECOME
                  SUBJECT TO THOSE RULES. WE URGE YOU TO REVIEW THE RULES OF
                  PARTICIPATION BEFORE YOU PARTICIPATE IN ANY PROMOTION LISTED
                  ON THE SITE. PROMOTION RULES WILL HAVE CONTROL TOWARDS ANY
                  CONFLICT OVER THESE TERMS & CONDITIONS.
                </p>
              </dd>

              <dt className="col-sm-3">
                VIOLATION OF THESE TERMS & CONDITIONS:
              </dt>
              <dd className="col-sm-9">
                <p>
                  WE MAY INVESTIGATE ANY VIOLATION IF FOUND RESPONSIBLE AGAINST
                  THESE TERMS & CONDITIONS AS REPRESENTED, INCLUDING
                  UNAUTHORIZED USE OF THE SITE. WE MAY PROVIDE LAW ENFORCEMENT
                  WITH INFORMATION YOU PROVIDE TO US RELATED TO YOUR
                  TRANSACTIONS TO ASSIST IN ANY INVESTIGATION OR PROSECUTION
                  TOWARDS YOU. WE MAY TAKE LEGAL ACTION THAT WE FEEL IS
                  APPROPRIATE. YOU AGREE THAT MONETARY DAMAGES MAY NOT PROVIDE
                  US A SUFFICIENT REMEDY AND THAT WE MAY PURSUE INJUNCTIVE OR
                  OTHER RELIEF FOR YOUR VIOLATION OF THESE TERMS & CONDITIONS AS
                  REPRESENTED. IF WE DETERMINE THAT YOU HAVE VIOLATED THESE
                  TERMS & CONDITIONS GUIDED OR THE LAW, OR FOR ANY OTHER REASON
                  OR FOR NO REASON, WE MAY CANCEL YOUR ACCOUNT, DELETE ALL YOUR
                  USER CONTENT AND PREVENT YOU FROM ACCESSING THE SITE AT ANY
                  TIME WITHOUT NOTICE TO YOU. IF THAT HAPPENS, YOU MAY NO LONGER
                  USE THE SITE OR ANY CONTENT. YOU WILL STILL BE BOUND BY YOUR
                  OBLIGATIONS UNDER THESE TERMS & CONDITIONS AS REPRESENTED. YOU
                  AGREE THAT WE WILL NOT BE LIABLE TO YOU OR ANY 3RD PARTY FOR
                  TERMINATION OF YOUR ACCESS TO THE SITE OR TO YOUR ACCOUNT OR
                  ANY RELATED INFORMATION, AND WE WILL NOT BE REQUIRED TO MAKE
                  THE SITE OR YOUR ACCOUNT OR ANY RELATED INFORMATION AVAILABLE
                  TO YOU. WE MAY ALSO CANCEL ANY ORDER AND PRODUCTS ACQUIRED
                  THROUGH YOUR ACCOUNT. WE MAY REFUSE TO HONOR PENDING AND
                  FUTURE PURCHASES MADE FROM ALL ACCOUNTS WE BELIEVE MAY BE
                  ASSOCIATED WITH YOU, OR CANCEL AN ORDER ASSOCIATED WITH ANY
                  PERSON WE BELIEVE TO BE ACTING WITH YOU, OR EXERCISE ANY OTHER
                  REMEDY AVAILABLE TO US. YOU AGREE THAT YOUR ABUSIVE USE OF THE
                  SITE MAY CAUSE DAMAGE AND HARM TO US, INCLUDING IMPAIRED
                  GOODWILL, LOST SALES AND INCREASED EXPENSES. YOU ALSO AGREE
                  THAT MONETARY DAMAGES FOR YOUR ABUSIVE USE OF THE SITE ARE
                  DIFFICULT TO DETERMINE AND THAT IF YOU, OR OTHERS ACTING WITH
                  YOU, REQUEST MORE THAN DEFAULT ACCESSIBLE TO THE SITE OR MAKE
                  MORE THAN DEFAULT ACCESSIBLE RESERVE REQUESTS ON THE SITE IN
                  ANY 24-HOUR PERIOD, YOU, AND THOSE ACTING WITH YOU, WILL BE
                  JOINTLY AND SEVERALLY LIABLE FOR LIQUIDATED DAMAGES IN THE
                  AMOUNT OF ONE HUNDRED RUPEES (INR 100/-) VALUED IN INDIAN
                  CURRENCY FOR EACH REQUEST OR RESERVE REQUEST MADE DURING THAT
                  24-HOUR PERIOD WHICH EXCEEDS THOSE DEFAULT ACCESSIBLE LIMITS.
                </p>
              </dd>

              <dt className="col-sm-3">DISCLAIMER OF WARRANTIES:</dt>
              <dd className="col-sm-9">
                <p>
                  WE PROVIDE THE SITE AND THE CONTENT TO YOU “AS IS” AND “AS
                  AVAILABLE”. WE TRY TO KEEP THE SITE UP, BUG-FREE AND SAFE, BUT
                  YOU USE IT AT YOUR OWN RISK. TO THE FULLEST EXTENT PERMISSIBLE
                  BY LAW. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED,
                  INCLUDING ANY WARRANTY OF TITLE, NON-INFRINGEMENT, ACCURACY,
                  MERCHANTABILITY, FIT FOR A PARTICULAR PURPOSE, OR WARRANTIES
                  THAT MAY ARISE FROM COURSE OF DEALING OR COURSE OF PERFORMANCE
                  OR USAGE OF TRADE. WE DO NOT GUARANTEE THAT THE SITE WILL
                  ALWAYS BE SAFE, SECURE OR ERROR-FREE OR THAT THE SITE WILL
                  ALWAYS FUNCTION WITHOUT DISRUPTIONS, DELAYS OR IMPERFECTIONS
                  DUE TO TECHNICAL ERRORS. WE ARE NOT RESPONSIBLE FOR THE
                  ACTIONS OR INFORMATION OF ANY 3RD PARTIES, AND YOU RELEASE US
                  FROM ANY CLAIMS AND DAMAGES, KNOWN AND UNKNOWN, ARISING OUT OF
                  OR IN ANY WAY CONNECTED WITH ANY CLAIM YOU HAVE AGAINST ANY
                  SUCH 3RD PARTIES. SOME JURISDICTIONS DO NOT ALLOW THE
                  EXCLUSION OF IMPLIED WARRANTIES, SO SOME OF THESE EXCLUSIONS
                  MAY NOT APPLY TO YOU. IF YOU ARE A RESIDENT OF BENGALURU
                  DISTRICT, KARNATAKA, INDIA, YOU CAN WAIVE BANGALORE CIVIL CODE
                  198013
                  <br />
                  <Link to="https://www.indiacode.nic.in/handle/123456789/7591?view_type=browse&sam_handle=123456789/2485">
                    YOU MAY FIND MORE INFORMATION ON:
                    HTTPS://INDIACODE.NIC.IN/HANDLE/123456789/7591?VIEW_TYPE=BROWSE&SAM_HANDLE=123456789/2485
                  </Link>
                </p>
              </dd>

              <dt className="col-sm-3">LIMITATION OF LIABILITY:</dt>
              <dd className="col-sm-9">
                <p>
                  IN NO EVENT WILL NEROLIFE NETWORKS OR OUR EVENT PROVIDERS,
                  SUPPLIERS, ADVERTISERS AND SPONSORS, BE RESPONSIBLE OR LIABLE
                  TO YOU OR ANYONE ELSE FOR, AND YOU HEREBY KNOWINGLY AND
                  EXPRESSLY WAIVE ALL RIGHTS TO SEEK, DIRECT, INDIRECT,
                  INCIDENTAL, SPECIAL, ACCIDENTAL OR CONSEQUENTIAL DAMAGES OF
                  ANY TYPE TO US OR OUR EVENT PROVIDERS, SUPPLIERS, ADVERTISERS
                  AND SPONSORS, AND ANY RIGHTS TO HAVE DAMAGES MULTIPLIED OR
                  OTHERWISE INCREASED, ARISING OUT OF OR IN CONNECTION WITH THE
                  SITE, THE CONTENT, OR ANY PRODUCT OR SERVICE PURCHASED THROUGH
                  THE SITE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF
                  SUCH DAMAGES, AND REGARDLESS OF WHETHER THE CLAIM IS BASED
                  UPON ANY CONTRACT, TORT, OR OTHER LEGAL OR EQUITABLE THEORY.
                  WITHOUT LIMITING THE FOREGOING, YOU EXPRESSLY ACKNOWLEDGE AND
                  AGREE THAT WE WILL HAVE NO LIABILITY OR RESPONSIBILITY
                  WHATSOEVER FOR (A) ANY ACTION OF ANOTHER USER ACTING ON YOUR
                  BEHALF OF THE SITE TO CONFORM TO THE CODES OF CONDUCT (B)
                  PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER,
                  WHETHER ARISING IN CONTRACT OR IN TORT, RESULTING FROM YOUR
                  ACCESS TO AND USE OF OUR SITE (C) ANY UNAUTHORIZED ACCESS TO
                  OR USE OF OUR SECURED ACTIVE SERVERS AND/OR ANY AND ALL
                  PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED
                  THEREIN (D) ANY BUGS, VIRUSES, WORMS, TROJAN HORSES, DEFECTS,
                  DATE BOMBS, TIME TRAPS OR OTHER ITEMS OF A DESTRUCTIVE NATURE
                  WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SITE DUE TO YOUR
                  ACTION (E) ANY ERRORS, MISTAKES, INACCURACIES OR OMISSIONS IN
                  ANY CONTENT. YOUR SOLE AND EXCLUSIVE REMEDY FOR
                  DISSATISFACTION WITH THE SITE IS TO STOP USING THE SITE. THE
                  LIMITATIONS IN THIS SECTION WILL APPLY EVEN IF ANY LIMITED
                  REMEDY FAILS OF ITS ESSENTIAL PURPOSE. THE ALLOCATION OF RISK
                  BETWEEN US IS AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN
                  BETWEEN US. OUR AGGREGATE LIABILITY ARISING OUT OF THESE TERMS
                  & CONDITIONS OR THE USE OF THE SITE WILL NOT EXCEED THE
                  GREATER OF SEVEN THOUSAND RUPEES (INR 7000/-) VALUED UPON
                  INDIAN CURRENCY OR THE MINIMUM AMOUNT YOU HAVE PAID US IN THE
                  PAST TWELVE MONTHS TO BE DECIDED ACCORDING TO THE
                  INVESTIGATION AS REQUIRED. SOME JURISDICTIONS DO NOT ALLOW THE
                  EXCLUSION OR LIMITATION OF DAMAGES, SO THESE MAY NOT APPLY TO
                  YOU. IN SUCH CASES, OUR LIABILITY WILL BE LIMITED TO THE
                  FULLEST EXTENT PERMITTED BY APPLICABLE LAW. IN NO EVENT WILL
                  ATTORNEYS’ FEES BE AWARDED OR RECOVERABLE.
                </p>
              </dd>

              <dt className="col-sm-3">INDEMNIFICATION:</dt>
              <dd className="col-sm-9">
                <p>
                  IF ANYONE BRINGS A CLAIM AGAINST US RELATED TO YOUR USE OF THE
                  SITE, THE CONTENT, YOUR USER CONTENT OR YOUR VIOLATION OF
                  THESE TERMS & CONDITIONS AS REPRESENTED, YOU AGREE TO
                  INDEMNIFY, DEFEND AND HOLD US AND OUR AFFILIATED COMPANIES,
                  EVENT PROVIDERS, SUPPLIERS, ADVERTISERS AND SPONSORS, AND EACH
                  OF OUR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS, HARMLESS
                  FROM AND AGAINST ANY AND ALL CLAIMS, DAMAGES, LOSSES AND
                  EXPENSES OF ANY KIND (INCLUDING REASONABLE LEGAL FEES AND
                  COSTS). WE RESERVE THE RIGHT TO TAKE EXCLUSIVE CONTROL AND
                  DEFENSE OF ANY CLAIM, AND YOU WILL COOPERATE FULLY WITH US IN
                  ASSERTING ANY AVAILABLE DEFENSES.
                </p>
              </dd>

              <dt className="col-sm-3">
                DISPUTES, INCLUDING MANDATORY ARBITRATION AND CLASS ACTION
                WAIVER:
              </dt>
              <dd className="col-sm-9">
                <p>
                  ANY DISPUTE OR CLAIM RELATING IN ANY WAY TO YOUR USE OF THE
                  SITE, OR TO PRODUCTS OR SERVICES SOLD OR DISTRIBUTED BY US OR
                  THROUGH US, WILL BE RESOLVED BY BINDING ARBITRATION RATHER
                  THAN IN COURT, WITH THE FOLLOWING EXCEPTIONS: YOU MAY ASSERT
                  CLAIMS IN SMALL CLAIMS COURT IF YOUR CLAIMS APPLY IF A CLAIM
                  INVOLVES THE CONDITIONAL LICENSE GRANTED TO YOU AS DESCRIBED
                  IN THE OWNERSHIP OF CONTENT AND GRANT OF CONDITIONAL LICENSE
                  SECTION ABOVE, EITHER OF US MAY FILE A LAWSUIT IN A FEDERAL OR
                  CITY COURT LOCATED WITHIN BENGALURU DISTRICT, KARNATAKA,
                  INDIA, AND WE BOTH CONSENT TO THE JURISDICTION OF THOSE COURTS
                  FOR SUCH PURPOSES IN THE EVENT THAT THE ARBITRATION AGREEMENT
                  IN THESE TERMS & CONDITIONS AS REPRESENTED IS FOR ANY REASON
                  HELD TO BE UNENFORCEABLE, ANY LITIGATION AGAINST US (EXCEPT
                  FOR SMALL-CLAIMS COURT ACTIONS) MAY BE COMMENCED ONLY IN A
                  FEDERAL OR CITY COURT LOCATED WITHIN BENGALURU DISTRICT,
                  KARNATAKA, INDIA, AND WE BOTH CONSENT TO THE JURISDICTION OF
                  THOSE COURTS FOR SUCH PURPOSES. THE ARBITRATION AGREEMENT IN
                  THESE TERMS & CONDITIONS AS REPRESENTED IS GOVERNED BY THE
                  INDIAN COUNCIL OF ARBITRATION (ICA) UNDER THE GOVERNMENT OF
                  INDIA, INCLUDING ITS PROCEDURAL PROVISIONS, IN ALL RESPECTS.
                  THIS MEANS THAT THE ICA GOVERNS, AMONG OTHER THINGS, THE
                  INTERPRETATION AND ENFORCEMENT OF THIS ARBITRATION AGREEMENT
                  AND ALL OF ITS PROVISIONS, INCLUDING, WITHOUT LIMITATION, THE
                  CLASS ACTION WAIVER DISCUSSED BELOW. STATE ARBITRATION LAWS DO
                  NOT GOVERN IN ANY RESPECT. THIS ARBITRATION AGREEMENT IS
                  INTENDED TO BE BROADLY INTERPRETED, AND WILL SURVIVE
                  TERMINATION OF THESE TERMS & CONDITIONS AS REPRESENTED. THE
                  ARBITRATOR, AND NOT ANY FEDERAL, STATE OR LOCAL COURT OR
                  AGENCY, SHALL HAVE EXCLUSIVE AUTHORITY TO THE EXTENT PERMITTED
                  BY LAW TO RESOLVE ALL DISPUTES ARISING OUT OF OR RELATING TO
                  THE INTERPRETATION, APPLICABILITY, ENFORCEABILITY OR FORMATION
                  OF THIS AGREEMENT, INCLUDING, BUT NOT LIMITED TO ANY CLAIM
                  THAT ALL OR ANY PART OF THIS AGREEMENT IS VOID OR VOIDABLE.
                  THERE IS NO JUDGE OR JURY IN ARBITRATION, AND COURT REVIEW OF
                  AN ARBITRATION AWARD IS LIMITED. HOWEVER, AN ARBITRATOR CAN
                  AWARD ON AN INDIVIDUAL BASIS THE SAME DAMAGES AND RELIEF AS A
                  COURT (INCLUDING INJUNCTIVE AND DECLARATORY RELIEF OR
                  STATUTORY DAMAGES), AND MUST FOLLOW THESE TERMS AS A COURT
                  WOULD. TO BEGIN AN ARBITRATION PROCEEDING, YOU MUST SEND A
                  LETTER REQUESTING ARBITRATION THROUGH LEGAL COUNCIL AND
                  DESCRIBING YOUR CLAIM TO: NEROLIFE NETWORKS PVT. LTD., #17
                  KIRLOSKAR, 1ST CROSS, SAPTAGIRI, BENGALURU, KA 560073 ATTN:
                  LEGAL. YOU MAY DOWNLOAD THE FORMS LOCATED AT
                  HTTP://WWW.ICAINDIA.CO.IN/ THE ARBITRATION WILL BE CONDUCTED
                  BY ICA UNDER ITS STREAMLINED ARBITRATION RULES AND PROCEDURES
                  OR, IF APPLICABLE, ITS COMPREHENSIVE ARBITRATION RULES AND
                  PROCEDURES, AND ANY APPLICABLE SUPPLEMENTAL RULES INCLUDING
                  ITS CONSUMER ARBITRATION STANDARDS OF MINIMUM FAIRNESS. THE
                  ICA RULES ARE AVAILABLE ONLINE AT HTTP://WWW.ICAINDIA.CO.IN/
                  PAYMENT OF ALL FILING, ADMINISTRATION AND ARBITRATOR FEES WILL
                  BE GOVERNED BY ICA’S RULES. WE WILL REIMBURSE THOSE FEES FOR
                  CLAIMS TOTALING LESS THAN INR 10,000 VALUED IN INDIAN CURRENCY
                  UNLESS THE ARBITRATOR DETERMINES THE CLAIMS ARE FRIVOLOUS, BUT
                  IN NO EVENT WILL WE PAY FOR ATTORNEYS’ FEES. YOU MAY CHOOSE TO
                  HAVE THE ARBITRATION CONDUCTED BY EMAIL, BASED ON WRITTEN
                  SUBMISSIONS, OR IN PERSON IN THE AREA WHERE YOU LIVE OR AT
                  ANOTHER MUTUALLY AGREED LOCATION. WE EACH AGREE THAT THE
                  ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON’S CLAIMS,
                  AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A
                  REPRESENTATIVE OR CLASS PROCEEDING, AND THAT ANY DISPUTE
                  RESOLUTION PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL
                  BASIS AND NOT IN A CLASS, CONSOLIDATED OR REPRESENTATIVE
                  ACTION. YOU AGREE TO WAIVE ANY RIGHT TO A JURY TRIAL OR TO
                  PARTICIPATE IN A CLASS ACTION. IF THIS SPECIFIC PROVISION IS
                  FOUND TO BE UNENFORCEABLE, THEN THE ENTIRETY OF THIS
                  ARBITRATION SECTION WILL BE NULL AND VOID AND NEITHER OF US
                  WILL BE ENTITLED TO ARBITRATE OUR DISPUTE. YOU AGREE THAT
                  THESE TERMS & CONDITIONS AS REPRESENTED EVIDENCE A TRANSACTION
                  INVOLVING INTERSTATE COMMERCE AND WILL BE GOVERNED BY AND
                  CONSTRUED IN ACCORDANCE WITH FEDERAL LAW TO THE FULLEST EXTENT
                  POSSIBLE UNDER THE GOVERNMENT OF INDIA.
                </p>
              </dd>

              <dt className="col-sm-3">QUESTIONS & QUERIES:</dt>
              <dd className="col-sm-9">
                <p>
                  IF YOU HAVE ANY QUESTIONS ABOUT SOLUTIONS, QUERIES ABOUT OUR
                  SERVICES, ANY COMMENTS OR COMPLAINTS REGARDING THESE TERMS &
                  CONDITIONS AS REPRESENTED OR THE SITE, PLEASE CONTACT OUR
                  CUSTOMER ASSISTANCE UNIT AT:
                  <br /> <br />
                  NEROLIFE NETWORKS PVT. LTD.
                  <br />
                  #17 KIRLOSKAR, 1ST CROSS
                  <br />
                  SAPTAGIRI, BENGALURU, KA 560073, INDIA
                  <br />
                  (+91) 9740619310 / (+91) 9916452130
                  <br />
                  EMAIL : NEROLIFEEXCLUSIVENETWORKS@GMAIL.COM
                  <br />
                  <br />
                  BENGALURU USERS MAY ALSO CONTACT THE COMPLAINT ASSISTANCE UNIT
                  OF THE DIVISION OF CONSUMER SERVICES, DEPARTMENT OF CONSUMER
                  AFFAIRS, BENGALURU, KARNATAKA, INDIA.
                  <br />
                  <br />
                  <Link to="https://consumeraffairs.nic.in/bangalore-urban-0">
                    FOR MORE INFORMATION :
                    HTTPS://CONSUMERAFFAIRS.NIC.IN/BANGALORE-URBAN-0
                  </Link>
                </p>
              </dd>
            </dl>
          </p>
        </figcaption>
      </figure>
    </div>
  );
};

export default TermsAndConditions;
